<?php

use Illuminate\Database\Seeder;

class AnotacionesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('anotaciones')->delete();
        
        \DB::table('anotaciones')->insert(array (
            0 => 
            array (
                'id' => 1,
                'proceso_id' => 2,
                'fecha_anotacion' => NULL,
                'asunto' => 'ACUERDO Y SUSPENSION',
                'descripcion' => 'TRABAJO ING. MARIO BERNAL ',
                'recordatorio' => NULL,
                'notificado' => 'No',
                'user_create_id' => 109,
                'user_update_id' => 118,
                'created_at' => '2019-08-23 15:25:26',
                'updated_at' => '2019-08-23 15:25:26',
            ),
            1 => 
            array (
                'id' => 2,
                'proceso_id' => 1,
                'fecha_anotacion' => NULL,
                'asunto' => 'inicio ',
                'descripcion' => 'ughuyggjhghj',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 2,
                'user_update_id' => 0,
                'created_at' => '2019-08-23 11:39:16',
                'updated_at' => '2019-08-23 11:39:16',
            ),
            2 => 
            array (
                'id' => 3,
                'proceso_id' => 3,
                'fecha_anotacion' => NULL,
                'asunto' => 'NOT 08/07/19',
                'descripcion' => 'TRABAJO COONALCETECE',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:22:04',
                'updated_at' => '2019-08-24 09:22:04',
            ),
            3 => 
            array (
                'id' => 4,
                'proceso_id' => 4,
                'fecha_anotacion' => NULL,
                'asunto' => 'AVISO 10-07-19',
                'descripcion' => 'TRABAJO ANITU LTDA NO LABORA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:24:50',
                'updated_at' => '2019-08-24 09:24:50',
            ),
            4 => 
            array (
                'id' => 5,
                'proceso_id' => 5,
                'fecha_anotacion' => NULL,
                'asunto' => 'SIN PENDIENTE',
                'descripcion' => 'TRABAJO YARA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:27:17',
                'updated_at' => '2019-08-24 09:27:17',
            ),
            5 => 
            array (
                'id' => 6,
                'proceso_id' => 6,
                'fecha_anotacion' => NULL,
                'asunto' => 'SIN PENDIENTE',
                'descripcion' => 'TRABAJO AUTOMOVIL',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:28:57',
                'updated_at' => '2019-08-24 09:28:57',
            ),
            6 => 
            array (
                'id' => 7,
                'proceso_id' => 7,
                'fecha_anotacion' => NULL,
                'asunto' => 'SIN PENDIENTE',
                'descripcion' => 'EMPRESA GRAN COLOMBIA GOLD',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:30:46',
                'updated_at' => '2019-08-24 09:30:46',
            ),
            7 => 
            array (
                'id' => 8,
                'proceso_id' => 8,
                'fecha_anotacion' => NULL,
                'asunto' => 'SIN PENDIENTE',
                'descripcion' => 'EMPRESA/ POLICIA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:32:14',
                'updated_at' => '2019-08-24 09:32:14',
            ),
            8 => 
            array (
                'id' => 9,
                'proceso_id' => 9,
                'fecha_anotacion' => NULL,
                'asunto' => 'SIN PENDIENTE',
                'descripcion' => 'EMPRESA / POSTOBON S.A',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:37:40',
                'updated_at' => '2019-08-24 09:37:40',
            ),
            9 => 
            array (
                'id' => 10,
                'proceso_id' => 10,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA /ENERGIA / AUTO ADMISORIO FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:41:43',
                'updated_at' => '2019-08-24 09:41:43',
            ),
            10 => 
            array (
                'id' => 11,
                'proceso_id' => 11,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA -BCO //AUTO ADMISORIO FIRME /PENDINTE ACUERDO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:44:22',
                'updated_at' => '2019-08-24 09:44:22',
            ),
            11 => 
            array (
                'id' => 12,
                'proceso_id' => 12,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA -COEXITO SAS //SIN PENDIENTE // AUTO ADMISORIO FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 09:46:32',
                'updated_at' => '2019-08-24 09:46:32',
            ),
            12 => 
            array (
                'id' => 13,
                'proceso_id' => 13,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'NO LABORA //PENDIENTE NOT 26-06-2019 ///AUTO ADMISORIO 08-03-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:00:43',
                'updated_at' => '2019-08-24 10:00:43',
            ),
            13 => 
            array (
                'id' => 14,
                'proceso_id' => 14,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'EMPLEO EJERCITO / PENDIENTE NOT 18-07-2019 //AUTO ADMISORIO 10-04-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:03:03',
                'updated_at' => '2019-08-24 10:03:03',
            ),
            14 => 
            array (
                'id' => 15,
                'proceso_id' => 15,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'TRABAJO - PRODUCCIONES RICO //PENDIENTE AVISO 14-06-2019 ///AUTO ADMISORIO 23-04-2019///PEREIRA JUZGADO 2',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:06:01',
                'updated_at' => '2019-08-24 10:06:01',
            ),
            15 => 
            array (
                'id' => 16,
                'proceso_id' => 16,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'EMPRESA MINEROS NACIONALES///PENDIENTE AVISO 03-07-2019 ///AUTO ADMISORIO 26-04-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:08:43',
                'updated_at' => '2019-08-24 10:08:43',
            ),
            16 => 
            array (
                'id' => 17,
                'proceso_id' => 4,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'COD: EMPRESA SEDET S.A///PENDIENTE AVISO 10-07-2019 ///AUTO ADMISORIO PTE RECLAMAR OFICIO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:13:51',
                'updated_at' => '2019-08-24 10:13:51',
            ),
            17 => 
            array (
                'id' => 18,
                'proceso_id' => 17,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'EMPRESA COOP MULTIACTIVA //PENDIENTE AVISO 13-07-2019 ///AUTO ADMISORIO 04-06-2019 /// PENTE RECLAMAR OFICIO ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:19:27',
                'updated_at' => '2019-08-24 10:19:27',
            ),
            18 => 
            array (
                'id' => 19,
                'proceso_id' => 18,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'EMPRESA COLCHONES HAPPY SLEEP ///PENDIENTE AVISO 24-07-2019 ///AUTO ADMISORIO 17-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:22:12',
                'updated_at' => '2019-08-24 10:22:12',
            ),
            19 => 
            array (
                'id' => 20,
                'proceso_id' => 19,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'EMPRESA CAMARA COMERCIO ///PENDIENTE NOT 03-07-2019///AUTO ADMISORIO 13/06/2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:29:13',
                'updated_at' => '2019-08-24 10:29:13',
            ),
            20 => 
            array (
                'id' => 21,
                'proceso_id' => 20,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADA CODEUDORA',
                'descripcion' => 'EMPRESA INTERNACIONAL DE ELECTRICO ///PENDIENTE NOT 03-07-2019//AUTO ADMISORIO 13-06-2019 ///05-08-2019 MEDIDA X LABORAL ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:51:16',
                'updated_at' => '2019-08-24 10:51:16',
            ),
            21 => 
            array (
                'id' => 22,
                'proceso_id' => 21,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'EMPRESA ALMACEN EXITO ///SIN PENDIENTE ///SIN AUTO ADMISORIO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-24 10:54:58',
                'updated_at' => '2019-08-24 10:54:58',
            ),
            22 => 
            array (
                'id' => 23,
                'proceso_id' => 22,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'TRABAJO ASESORIA E INGENIERIA ///PENDIENTE AVISO 14-06-19 OK///AUTOADMISORIO 24-04-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-27 11:59:11',
                'updated_at' => '2019-08-27 11:59:11',
            ),
            23 => 
            array (
                'id' => 24,
                'proceso_id' => 23,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'TRABAJO ATEXCO ///PENDIENTE NOT 08-07-2019 ///AUTOADMISORIO 30-05-2019/// 05-08-2019 PTE MEDIDA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 118,
                'created_at' => '2019-08-27 12:23:11',
                'updated_at' => '2019-08-27 12:23:11',
            ),
            24 => 
            array (
                'id' => 25,
                'proceso_id' => 24,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDADO',
                'descripcion' => 'TRABAJO ATENTO//PENDIENTE NOT 08-07-2019///AUTO ADMISORIO 29-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-08-27 12:21:29',
                'updated_at' => '2019-08-27 12:21:29',
            ),
            25 => 
            array (
                'id' => 26,
                'proceso_id' => 25,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA TRANS NORMA// PENDIENTE AVISO 03-07-2019 OK///AUTO ADMISORIO 12-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:11:55',
                'updated_at' => '2019-09-11 15:11:55',
            ),
            26 => 
            array (
                'id' => 27,
                'proceso_id' => 26,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA ALCALDIA //PENDIENTE ACUERDO ///AUTO ADMISORIO FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:19:10',
                'updated_at' => '2019-09-11 15:19:10',
            ),
            27 => 
            array (
                'id' => 28,
                'proceso_id' => 27,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: COLCHONES EL REY ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:24:31',
                'updated_at' => '2019-09-11 15:24:31',
            ),
            28 => 
            array (
                'id' => 29,
                'proceso_id' => 28,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: COOTRASERBU',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:25:51',
                'updated_at' => '2019-09-11 15:25:51',
            ),
            29 => 
            array (
                'id' => 30,
                'proceso_id' => 29,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: COMAPAN S.A',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:27:07',
                'updated_at' => '2019-09-11 15:27:07',
            ),
            30 => 
            array (
                'id' => 31,
                'proceso_id' => 30,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: AUTOMIVIL',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:28:16',
                'updated_at' => '2019-09-11 15:28:16',
            ),
            31 => 
            array (
                'id' => 32,
                'proceso_id' => 31,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: MAKRO //PENDIENTE: 10-04-18 MEDIDAS //AUTO ADMISORIO: FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:31:43',
                'updated_at' => '2019-09-11 15:31:43',
            ),
            32 => 
            array (
                'id' => 33,
                'proceso_id' => 32,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'PENDIENTE: ACUERDO // AUTO ADMISORIO: FIRME // OBSERVACIONES: GESTIÓN LEGAL',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:33:55',
                'updated_at' => '2019-09-11 15:33:55',
            ),
            33 => 
            array (
                'id' => 34,
                'proceso_id' => 33,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: APOYO AERONÁUTICO //AUTO ADMISORIO: FIRME // OBSERVACIONES: LIQUIDACIÓN 16-06-2019// ACUERDO ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:36:55',
                'updated_at' => '2019-09-11 15:36:55',
            ),
            34 => 
            array (
                'id' => 35,
                'proceso_id' => 34,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: INVERSIONES URREA S.A.S // AUTO ADMISORIO: FIRME ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:38:24',
                'updated_at' => '2019-09-11 15:38:24',
            ),
            35 => 
            array (
                'id' => 36,
                'proceso_id' => 35,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: FERREINOX LTDA // PENDIENTE: ACUERDO // AUTO ADMISORIO: FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:40:09',
                'updated_at' => '2019-09-11 15:40:09',
            ),
            36 => 
            array (
                'id' => 37,
                'proceso_id' => 36,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: MINA LA SOMBRA // AUTO ADMISORIO: 11-07-2018',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:42:28',
                'updated_at' => '2019-09-11 15:42:28',
            ),
            37 => 
            array (
                'id' => 38,
                'proceso_id' => 37,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: TECNI FRÍOS // PENDIENTE: NOT 15-05-19 OK // AUTO ADMISORIO:24-04-2019 // OBSERVACIONES: ACUERDO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:45:45',
                'updated_at' => '2019-09-11 15:45:45',
            ),
            38 => 
            array (
                'id' => 39,
                'proceso_id' => 38,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: MOTOCICLETA // PENDIENTE: AVISO 30-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:47:39',
                'updated_at' => '2019-09-11 15:47:39',
            ),
            39 => 
            array (
                'id' => 40,
                'proceso_id' => 39,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: POLLO EL BUCANEROS // PENDIENTE: AVISO 03-07-2019 // AUTO ADMISORIO: 09-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:54:52',
                'updated_at' => '2019-09-11 15:54:52',
            ),
            40 => 
            array (
                'id' => 41,
                'proceso_id' => 40,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: PROCESO COLORS SAS NO LABORA // PENDIENTE: SE PASÓ DE CASA Y NO LABORA //AUTO ADMISORIO:24-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:57:01',
                'updated_at' => '2019-09-11 15:57:01',
            ),
            41 => 
            array (
                'id' => 42,
                'proceso_id' => 41,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: DESGIN SA // PENDIENTE: AVISO 18-07-2019 // AUTO ADMISORIO: 18-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 15:58:53',
                'updated_at' => '2019-09-11 15:58:53',
            ),
            42 => 
            array (
                'id' => 43,
                'proceso_id' => 42,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: SEGURIDAD SUPERIOR // PENDIENTE: NOT 26-06-2019 // AUTO ADMISORIO: 11-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 16:01:05',
                'updated_at' => '2019-09-11 16:01:05',
            ),
            43 => 
            array (
                'id' => 44,
                'proceso_id' => 43,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: JOSÉ WILLIAM CALLE //PENDIENTE: AVISO 06-08-2019 // AUTO ADMISORIO: 03-07-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 16:03:44',
                'updated_at' => '2019-09-11 16:03:44',
            ),
            44 => 
            array (
                'id' => 45,
                'proceso_id' => 44,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: SEMI S.A.S // PENDIENTE: NOT 26-06-2019 OK // AUTO ADMISORIO: FIRME // OBSERVACIONES: ACUERDO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 16:20:02',
                'updated_at' => '2019-09-11 16:20:02',
            ),
            45 => 
            array (
                'id' => 46,
                'proceso_id' => 45,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: TABARES LÓPEZ INVERSIONES // ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 16:21:42',
                'updated_at' => '2019-09-11 16:21:42',
            ),
            46 => 
            array (
                'id' => 47,
                'proceso_id' => 46,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: INCPAC S.A //',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 16:24:49',
                'updated_at' => '2019-09-11 16:24:49',
            ),
            47 => 
            array (
                'id' => 48,
                'proceso_id' => 47,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: ACCIÓN // PENDIENTE:ACUERDO// AUTO ADMISORIO:FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 16:46:59',
                'updated_at' => '2019-09-11 16:46:59',
            ),
            48 => 
            array (
                'id' => 49,
                'proceso_id' => 48,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: POLICIA // PENDIENTE: LIQUIDACIÓN // AUTO ADMISORIO // FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 16:54:05',
                'updated_at' => '2019-09-11 16:54:05',
            ),
            49 => 
            array (
                'id' => 50,
                'proceso_id' => 49,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA:  UNV AUTÓNOMA // PENDIENTE: LIQUIDACIÓN OK // AUTO ADMISORIO: FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 16:58:48',
                'updated_at' => '2019-09-11 16:58:48',
            ),
            50 => 
            array (
                'id' => 51,
                'proceso_id' => 50,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: BCO //AUTO ADMISORIO: 03/07/2018',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 17:26:45',
                'updated_at' => '2019-09-11 17:26:45',
            ),
            51 => 
            array (
                'id' => 52,
                'proceso_id' => 51,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
            'descripcion' => 'EMPRESA INMUEBLE (NO VIVE) // PENDIENTE: 20-08-18 NOT (NO VIVE) // AUTO ADMISORIO: 06-07-2018',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 17:30:29',
                'updated_at' => '2019-09-11 17:30:29',
            ),
            52 => 
            array (
                'id' => 53,
                'proceso_id' => 52,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: ASOHOGARES',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 17:42:31',
                'updated_at' => '2019-09-11 17:42:31',
            ),
            53 => 
            array (
                'id' => 54,
                'proceso_id' => 53,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: EFICACIA S.A NO LABORA // AUTO ADMISORIO : 11-04-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 17:45:46',
                'updated_at' => '2019-09-11 17:45:46',
            ),
            54 => 
            array (
                'id' => 55,
                'proceso_id' => 54,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA:INMUEBLE // PENDIENTE: 06-08-2019  EMPLAZAMIENTO // AUTO ADMISORIO:28-05-2019 // OBSERVACIONES: 06-08-2019 ACREEDOR PRENDARIO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 17:48:40',
                'updated_at' => '2019-09-11 17:48:40',
            ),
            55 => 
            array (
                'id' => 56,
                'proceso_id' => 55,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: RADIO TAXI // PENDIENTE: AVISO 03-07-2019 // AUTO ADMISORIO: 30-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 17:50:42',
                'updated_at' => '2019-09-11 17:50:42',
            ),
            56 => 
            array (
                'id' => 57,
                'proceso_id' => 56,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: POLICIA NO LABORA //  PENDIENTE: NOT 03-07-2019 // AUTO ADMISORIO: 024-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 17:55:19',
                'updated_at' => '2019-09-11 17:55:19',
            ),
            57 => 
            array (
                'id' => 58,
                'proceso_id' => 57,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: AFISS CALI SAS // PENDIENTE: AVISO 15-07-2019 OK ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 17:57:30',
                'updated_at' => '2019-09-11 17:57:30',
            ),
            58 => 
            array (
                'id' => 59,
                'proceso_id' => 58,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: AUTOMOVIL // PENDIENTE: AVISO 18-07-2019 OK // AUTO ADMISORIO :13-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-11 18:00:54',
                'updated_at' => '2019-09-11 18:00:54',
            ),
            59 => 
            array (
                'id' => 60,
                'proceso_id' => 59,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: COLCHONES EL REY // PENDIENTE: NOT... 06-08-2019 ///AUTO ADMISORIO:  22-07-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 09:56:56',
                'updated_at' => '2019-09-12 09:56:56',
            ),
            60 => 
            array (
                'id' => 61,
                'proceso_id' => 60,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: MAC POLLO ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 09:58:36',
                'updated_at' => '2019-09-12 09:58:36',
            ),
            61 => 
            array (
                'id' => 62,
                'proceso_id' => 61,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: COOASBIEN',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 10:00:23',
                'updated_at' => '2019-09-12 10:00:23',
            ),
            62 => 
            array (
                'id' => 63,
                'proceso_id' => 62,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: NUTRIR//  PENDIENTE: EPS 26-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 10:03:32',
                'updated_at' => '2019-09-12 10:03:32',
            ),
            63 => 
            array (
                'id' => 64,
                'proceso_id' => 63,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: ILKO ARCASED // PENDIENTE: NOT 06-08-2019 // AUTO ADMISORIO : 20-03-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 10:11:40',
                'updated_at' => '2019-09-12 10:11:40',
            ),
            64 => 
            array (
                'id' => 65,
                'proceso_id' => 64,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: COOP DE AVIANCA NO LABORA //  PENDIENTE: NOT 22-05-19 NO VIVE // OBSERVACIONES: 06-08-2019 OFICIO EPS',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 10:15:04',
                'updated_at' => '2019-09-12 10:15:04',
            ),
            65 => 
            array (
                'id' => 66,
                'proceso_id' => 65,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: CÁMARA DE COMERCIO /// PENDIENTE: AVISO 14-06-19 OK // AUTO ADMISORIO: 15-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 10:18:06',
                'updated_at' => '2019-09-12 10:18:06',
            ),
            66 => 
            array (
                'id' => 67,
                'proceso_id' => 66,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: INST. DESCENTR DE BUGA // PENDIENTE: AVISO 18-07-2019 /// AUTO ADMISORIO: 10-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 10:23:55',
                'updated_at' => '2019-09-12 10:23:55',
            ),
            67 => 
            array (
                'id' => 68,
                'proceso_id' => 67,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA : CENTRO LOGÍSTICO // PENDIENTE: AVISO 18-07-2019 // AUTO ADMISORIO: 18/06/2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 14:42:23',
                'updated_at' => '2019-09-12 14:42:23',
            ),
            68 => 
            array (
                'id' => 69,
                'proceso_id' => 68,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: MINEROS NACIONALES // PENDIENTE: NOT 03-07-2019 // AUTO ADMISORIO: 18-06-2019 // OBSERVACIONES: MEDIDA 08-07-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 14:46:01',
                'updated_at' => '2019-09-12 14:46:01',
            ),
            69 => 
            array (
                'id' => 70,
                'proceso_id' => 69,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: ING COLOMBIANA NO LABORA // PENDIENTE: NOT 08-07-2019 // AUTO ADMISORIO: 20-06-2019.',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 14:50:18',
                'updated_at' => '2019-09-12 14:50:18',
            ),
            70 => 
            array (
                'id' => 71,
                'proceso_id' => 70,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: CROYDON // PENDIENTE: AVISO 18-07-2019 OK // AUTO ADMISORIO: 27-06-2019 // OBSERVACIONES: ACUERDO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 14:52:19',
                'updated_at' => '2019-09-12 14:52:19',
            ),
            71 => 
            array (
                'id' => 72,
                'proceso_id' => 71,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: MOTO // PENDIENTE: AVISO 18-07-2019 OK //AUTO ADMISORIO: 21-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 14:55:26',
                'updated_at' => '2019-09-12 14:55:26',
            ),
            72 => 
            array (
                'id' => 73,
                'proceso_id' => 72,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: ANITUR LTDA ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 14:58:14',
                'updated_at' => '2019-09-12 14:58:14',
            ),
            73 => 
            array (
                'id' => 74,
                'proceso_id' => 73,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: COLOMBIA TELECOMUNICACIONES ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:01:25',
                'updated_at' => '2019-09-12 15:01:25',
            ),
            74 => 
            array (
                'id' => 75,
                'proceso_id' => 74,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: LIFE CLEAN SA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:04:41',
                'updated_at' => '2019-09-12 15:04:41',
            ),
            75 => 
            array (
                'id' => 76,
                'proceso_id' => 75,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: CONFA // AUTO ADMISORIO: FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 137,
                'created_at' => '2019-09-12 15:09:38',
                'updated_at' => '2019-09-12 15:09:38',
            ),
            76 => 
            array (
                'id' => 77,
                'proceso_id' => 76,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: SERDAN : AUTO ADMISORIO : FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:11:04',
                'updated_at' => '2019-09-12 15:11:04',
            ),
            77 => 
            array (
                'id' => 78,
                'proceso_id' => 18,
                'fecha_anotacion' => NULL,
                'asunto' => 'CODEUDORA ALLYSON MARIA CARDONA- DEMANDA',
                'descripcion' => 'SE ANEXA DATOS DE DEMANDA DE LA CODEUDORA ALLYSON MARIA CARDONA JARAMILLO CC 1.053.809.931 // JUZGADO SEXTO CIVIL MUNICIPAL // RADICADO 2019-573 // FECHA 06-06-19 // EMPRESA: DEMPOS // PENDIENTE: AVISO 25-07-2019 // AUTO ADMISORIO: 05-07-2019 // OBSERVACIÓN: MEDIDA 10-07-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 137,
                'created_at' => '2019-09-12 15:21:10',
                'updated_at' => '2019-09-12 15:21:10',
            ),
            78 => 
            array (
                'id' => 79,
                'proceso_id' => 21,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA TITULAR',
                'descripcion' => 'SE RELACIONAN DATOS DE LA TITULAR // JUZGADO SEXTO CIVIL MUNICIPAL // RADICADO: 2019-799 // FECHA:25-07-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:26:42',
                'updated_at' => '2019-09-12 15:26:42',
            ),
            79 => 
            array (
                'id' => 80,
                'proceso_id' => 77,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: CENCOSUD NO LABORA // AUTO ADMISORIO: 23-05-2018',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:30:59',
                'updated_at' => '2019-09-12 15:30:59',
            ),
            80 => 
            array (
                'id' => 81,
                'proceso_id' => 78,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: MUEBLES DE LUJO // PENDIENTE: 13-02-2019 NOT //AUTO ADMISORIO: 06-08-2018',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:34:57',
                'updated_at' => '2019-09-12 15:34:57',
            ),
            81 => 
            array (
                'id' => 82,
                'proceso_id' => 79,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: ASOHOGARES // AUTO ADMISORIO: 01-04-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:45:43',
                'updated_at' => '2019-09-12 15:45:43',
            ),
            82 => 
            array (
                'id' => 83,
                'proceso_id' => 80,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: AUTOMOVIL // PENDIENTE: NOT 29-04-2019 // AUTO ADMISORIO: 12-04-2019 ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:49:29',
                'updated_at' => '2019-09-12 15:49:29',
            ),
            83 => 
            array (
                'id' => 84,
                'proceso_id' => 81,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: CÁMARA DE COMERCIO // PENDIENTE: -AVISO 18-07-2019 // AUTO ADMISORIO: 24-04-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 15:59:22',
                'updated_at' => '2019-09-12 15:59:22',
            ),
            84 => 
            array (
                'id' => 85,
                'proceso_id' => 82,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA:TROPI-ABASTOS //PENDIENTE: AVISO 30-05-19 OK // AUTO ADMISORIO: 26-04-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:14:34',
                'updated_at' => '2019-09-12 16:14:34',
            ),
            85 => 
            array (
                'id' => 86,
                'proceso_id' => 83,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: PINTU ACABADOS //',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:16:11',
                'updated_at' => '2019-09-12 16:16:11',
            ),
            86 => 
            array (
                'id' => 87,
                'proceso_id' => 84,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA:TECNI EXTINTORES // PENDIENTE: AVISO 18-07-2019 OK // AUTO ADMISORIO: 17-06-2019 // OBSERVACIONES: ACUERDO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:19:56',
                'updated_at' => '2019-09-12 16:19:56',
            ),
            87 => 
            array (
                'id' => 88,
                'proceso_id' => 33,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA TITULAR',
                'descripcion' => 'SE RELACIONAN DATOS TITULAR // JUZGADO: SÉPTIMO CIVIL MUNICIPAL // RADICADO: 2019-519 // FECHA: 29-05-2019 //EMPRESA: APOYO AERONÁUTICO // PENDIENTE:  ACUERDO // AUTO ADMISORIO: 14-06-2019 ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:24:24',
                'updated_at' => '2019-09-12 16:24:24',
            ),
            88 => 
            array (
                'id' => 89,
                'proceso_id' => 85,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: CARNICERÍA PACHOS // PENDIENTE: SE NOTIFICÓ // AUTO ADMISORIO: 28-06-2019 // OBSERVACIONES: ACUERDO.',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:32:20',
                'updated_at' => '2019-09-12 16:32:20',
            ),
            89 => 
            array (
                'id' => 90,
                'proceso_id' => 30,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA CODEUDORA MARIA NELLY MACHADO ',
                'descripcion' => 'SE RELACIONAN DATOS DE LA CODEUDORA MARÍA NELLY MACHADO DE ROJAS CC 28.619.921 // JUZGADO: SÉPTIMO CIVIL MUNICIPAL // RADICADO: 2019-757 // FECHA: 25-07-2019 //EMPRESA: INMUEBLE',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:36:16',
                'updated_at' => '2019-09-12 16:36:16',
            ),
            90 => 
            array (
                'id' => 91,
                'proceso_id' => 86,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: ADISPETROL S.A ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:38:37',
                'updated_at' => '2019-09-12 16:38:37',
            ),
            91 => 
            array (
                'id' => 92,
                'proceso_id' => 87,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA TECNI PERSONALES // ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:44:39',
                'updated_at' => '2019-09-12 16:44:39',
            ),
            92 => 
            array (
                'id' => 93,
                'proceso_id' => 88,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: INTER-RAPIDISIMO //AUTO ADMISORIO:12-04-2019 // OBSEVACIONES: ACUERDO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 16:49:26',
                'updated_at' => '2019-09-12 16:49:26',
            ),
            93 => 
            array (
                'id' => 94,
                'proceso_id' => 89,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: SEGURIDAD RVC // PENDIENTE: NOT... 13-05-2019 // AUTO ADMISORIO: 26-04-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 17:48:36',
                'updated_at' => '2019-09-12 17:48:36',
            ),
            94 => 
            array (
                'id' => 95,
                'proceso_id' => 90,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA:  GRAN COLOMBIA GOLD // PENDIENTE: NOT 03-07-2019 // AUTO ADMISORIO: 13-06-2019 // OBSERVACIONES: EPS 05-08-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 17:51:47',
                'updated_at' => '2019-09-12 17:51:47',
            ),
            95 => 
            array (
                'id' => 96,
                'proceso_id' => 91,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: ALIVAL NO LABORA // PENDIENTE:  AVISO 18-07-2019 //AUTO ADMISORIO: 07-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-12 17:54:42',
                'updated_at' => '2019-09-12 17:54:42',
            ),
            96 => 
            array (
                'id' => 97,
                'proceso_id' => 92,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA:  DOCENTE // PENDIENTE: TÍTULOS TERMINACIÓN // AUTO ADMISORIO: 03-06-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:25:55',
                'updated_at' => '2019-09-13 08:25:55',
            ),
            97 => 
            array (
                'id' => 98,
                'proceso_id' => 93,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: CÁMARA DE COMERCIO // PENDIENTE: NOT 03-07-2019 //AUTO ADMISORIO: 19-06-2019 // OBSERVACIONES: ACUERDO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:34:25',
                'updated_at' => '2019-09-13 08:34:25',
            ),
            98 => 
            array (
                'id' => 99,
                'proceso_id' => 60,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA - CODEUDOR ',
                'descripcion' => 'SE RELACIONAN DATOS DE CODEUDOR  WILLINGTON CORTES BERMÚDEZ // C.C 1.115.085.226 // JUZGADO: OCTAVO CIVIL MUNICIPAL // RADICADO:2019-778 // FECHA:25-07-2019 // EMPRESA: SEGURIDAD ATLAS SA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:38:38',
                'updated_at' => '2019-09-13 08:38:38',
            ),
            99 => 
            array (
                'id' => 100,
                'proceso_id' => 94,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: POLICIA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:39:54',
                'updated_at' => '2019-09-13 08:39:54',
            ),
            100 => 
            array (
                'id' => 101,
                'proceso_id' => 95,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: SISPRO // PENDIENTE: ACUERDO //AUTO ADMISORIO: FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:43:03',
                'updated_at' => '2019-09-13 08:43:03',
            ),
            101 => 
            array (
                'id' => 102,
                'proceso_id' => 96,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: GOBERNACIÓN DE RISARALDA // AUTOADMISORIO: FIRME // OBSERVACIONES: ACUERDO',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:46:39',
                'updated_at' => '2019-09-13 08:46:39',
            ),
            102 => 
            array (
                'id' => 103,
                'proceso_id' => 97,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: CAÑARTE // PENDIENTE: SE NOTIFICÓ // AUTO ADMISORIO: FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:48:40',
                'updated_at' => '2019-09-13 08:48:40',
            ),
            103 => 
            array (
                'id' => 104,
                'proceso_id' => 98,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: BCO // AUTO ADMISORIO: 25-07-2018',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:51:48',
                'updated_at' => '2019-09-13 08:51:48',
            ),
            104 => 
            array (
                'id' => 105,
                'proceso_id' => 97,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA - CODEUDOR',
                'descripcion' => 'SE RELACIONAN DATOS CODEUDOR JOHN ALEXANDER BETANOURTH VÉLEZ // C.C 1.116.248.564 // RADICACO: 2019-210 // FECHA: 22-05-2019 // EMPRESA: CAÑARTE //PENDIENTE: AVISO 06-08-2019 // AUTO ADMISORIO:31-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:55:23',
                'updated_at' => '2019-09-13 08:55:23',
            ),
            105 => 
            array (
                'id' => 106,
                'proceso_id' => 99,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: AVIORZA //PENDIENTE: AVISO 26-07-2019 // AUTO ADMISORIO: 31-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:57:57',
                'updated_at' => '2019-09-13 08:57:57',
            ),
            106 => 
            array (
                'id' => 107,
                'proceso_id' => 100,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: ARENAS Y GAVIONES SAS // PENDIENTE:  LIQUIDACIÓN 10-07-2019 // AUTO ADMISORIO: FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 08:59:57',
                'updated_at' => '2019-09-13 08:59:57',
            ),
            107 => 
            array (
                'id' => 108,
                'proceso_id' => 101,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: FRANCOL LTDA // PENDIENTE: AVISO 01-04-2019 // AUTO ADMISORIO: 08-08-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 09:02:37',
                'updated_at' => '2019-09-13 09:02:37',
            ),
            108 => 
            array (
                'id' => 109,
                'proceso_id' => 102,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'EMPRESA: MOTO //  PENDIENTE: EPS 05-08-2019 // AUTO ADMISORIO: 17-05-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 09:05:47',
                'updated_at' => '2019-09-13 09:05:47',
            ),
            109 => 
            array (
                'id' => 110,
                'proceso_id' => 103,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA ',
                'descripcion' => 'EMPRESA: PRINTEX // PENDIENTE: 22-03-2017 SOL. TITULOS / AUTO ADMISORIO: FIRME',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 09:08:46',
                'updated_at' => '2019-09-13 09:08:46',
            ),
            110 => 
            array (
                'id' => 111,
                'proceso_id' => 104,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA: ONCOLOGOS // PENDIENTE: CONVENIR TITULOS // AUTO ADMISORIO: FIRME // OBSRVACIONES: 12-04-2018 SOL. TITULOS',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 09:10:53',
                'updated_at' => '2019-09-13 09:10:53',
            ),
            111 => 
            array (
                'id' => 112,
                'proceso_id' => 105,
                'fecha_anotacion' => NULL,
                'asunto' => 'SENTENCIA',
                'descripcion' => 'EMPRESA:INMUEBLE // AUTO ADMISORIO: FIRME ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-13 09:16:11',
                'updated_at' => '2019-09-13 09:16:11',
            ),
            112 => 
            array (
                'id' => 113,
                'proceso_id' => 106,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICA DEMANDA EN EL JUZGADO OCTAVO CIVIL MCIPAL // RADICADO 2019-987 // 17/09/2019 // AL CODEUDOR VICTOR ADOLFO RESTREPO BERMÚDEZ C.C 18.521.727 ',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-17 17:21:14',
                'updated_at' => '2019-09-17 17:21:14',
            ),
            113 => 
            array (
                'id' => 114,
                'proceso_id' => 107,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR // JUZG. SÉPT CIVIL MPAL // RAD 2019-986// 17-09-2019 // LUGAR DE RESIDENCIA CRA 4 # 91-22 BARRIO VILLA NUEVA - IBAGUÉ // MEDIDA CAUTELAR 50% DE LOS INGRESOS Y DEMÁS RUBROS RECIBIDOS',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-18 09:02:39',
                'updated_at' => '2019-09-18 09:02:39',
            ),
            114 => 
            array (
                'id' => 115,
                'proceso_id' => 108,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR // JUZG. TER CIVIL MPAL // RAD. 2019-1003 // 17/09/2019 // LUGAR DE RESIDENCIA CALLE 14 No. 5-28 PEREIRA // MEDIDA CAUTELAR 50% DE LOS HONORARIOS, INGRESOS Y DEMÁS RUBROS RECIBIDOS',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-18 09:13:15',
                'updated_at' => '2019-09-18 09:13:15',
            ),
            115 => 
            array (
                'id' => 116,
                'proceso_id' => 109,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => ' SE RADICÓ DEMANDA AL TITULAR // JUZG. SEXTO CIVIL MPAL // RAD 2019-1015 // 17-09-2019 // RESIDENCIA CRA 8 No. 32-98 PEREIRA // MEDIDA CAUTELAR 50% DE LOS INGRESOS RECIBIDOS',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-18 09:19:57',
                'updated_at' => '2019-09-18 09:19:57',
            ),
            116 => 
            array (
                'id' => 117,
                'proceso_id' => 110,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA ',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR  // JUZG. QUINTO CIVIL MPAL // RAD. 2019-1006 // 17-09-2019 // EMPRESA CRA 15 No. 18-29 ANTIOQUEÑA DE LUBRICANTES PEREIRA // MEDIDA CAUTELAR 50% DE LOS INGRESOS RECIBIDOS.',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-18 09:25:12',
                'updated_at' => '2019-09-18 09:25:12',
            ),
            117 => 
            array (
                'id' => 118,
                'proceso_id' => 111,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR  // JUZG. PRIMERO CIVIL MPAL // RAD. 2019-0980 // 17-09-2019 // RESIDENCIA KRA 26-158 PEREIRA // MEDIDA CAUTELAR EMBARGO DEL 50% INMUEBLE MATR. 290-120834 MZ 1 LOTE 28 BARRIO OLIMPIA CIUDADELA CUBA - PEREIRA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-18 09:34:03',
                'updated_at' => '2019-09-18 09:34:03',
            ),
            118 => 
            array (
                'id' => 119,
                'proceso_id' => 112,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR // JUZG. CUARTO CIVIL MPAL // RAD. 2019-0984 // 17-09-2019 // EMPRESA EFICACIA SA  CALLE 14 No. 15-03 CIRCUNVALAR  PEREIRA // MEDIDA CAUTELAR 50% DE LOS INGRESOS RECIBIDOS',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-09-18 09:49:25',
                'updated_at' => '2019-09-18 09:49:25',
            ),
            119 => 
            array (
                'id' => 120,
                'proceso_id' => 113,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR DEL CRÉDITO // JUZG. SEPTIMO CIVIL MCPAL // RAD . 2019-1056 // 07/10/2019 // NOTIFICACIÓN EN RESIDENCIA CRA 11 No. 36-06  B/ BUENOS AIRES PEREIRA /// MEDIDA CAUTELAR 50% DE LOS INGRESOS',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-07 17:09:47',
                'updated_at' => '2019-10-07 17:09:47',
            ),
            120 => 
            array (
                'id' => 121,
                'proceso_id' => 114,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR // JUZG. CUARTO CIVIL MCPAL // RAD 2019-1055 // 07/10/2019 // MEDIDA CAUTELAR 50% DE LOS INGRESOS //  NOTIF. CALLE 26 No. 102-30 of 303 Administración de Redes y Proyectos sas de Bogotá',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-08 08:29:35',
                'updated_at' => '2019-10-08 08:29:35',
            ),
            121 => 
            array (
                'id' => 122,
                'proceso_id' => 115,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL CODEUDOR JULIO CESAR MORALES //JUZG. QUINTO CIVIL MCPAL // RAD 2019-1075 // 07/10/2019 // MEDIDA CAUTELAR 50% DE LOS INGRESOS // NOTIF. CALLE 13 No. 15-53 B/ LOS ALPES  INTEGRA S.A',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-08 08:34:01',
                'updated_at' => '2019-10-08 08:34:01',
            ),
            122 => 
            array (
                'id' => 123,
                'proceso_id' => 45,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR // JUZG. OCTAVO CIVIL MCPAL // RAD. 2019-1051 // 07/10/2019 // MEDIDA CAUTELAR 50% DE LOS INGRESOS // NOTIF. KRA 5 No. 35-38 PEREIRA',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-08 08:41:07',
                'updated_at' => '2019-10-08 08:41:07',
            ),
            123 => 
            array (
                'id' => 124,
                'proceso_id' => 116,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA A LA TITULAR // JUZG. SEGUNDO CIVIL MCPAL // RAD. 2019-1063 // 07/10/2019 // MEDIDA CAUTELAR 50% DE LOS INGRESOS // NOTIF. CALLE 10 No. 15-64 SEGURIDAD NACIONAL LTDA.',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-08 08:51:56',
                'updated_at' => '2019-10-08 08:51:56',
            ),
            124 => 
            array (
                'id' => 125,
                'proceso_id' => 117,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL CODEUDOR JOSÉ DUBERNEY HENAO // RAD. 2019-1064 // 07/10/2019 // MEDIDA CAUTELAR 50% DE LOS INGRESOS // NOTIF. CRA 16 No. 11-59 MOSARCOOP SANTA ROSA DE CABAL.',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-08 08:57:51',
                'updated_at' => '2019-10-08 08:57:51',
            ),
            125 => 
            array (
                'id' => 126,
                'proceso_id' => 118,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR // JUZG. TERCERO CIVIL MCPAL // RAD. 2019-1077 // 07/10/2019 // MEDIDA CAUTELAR 50% DE LOS INGRESOS // NOTIF. CALLE 8 No. 13 A -11 CARTAGO VALLE',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-08 09:00:50',
                'updated_at' => '2019-10-08 09:00:50',
            ),
            126 => 
            array (
                'id' => 127,
                'proceso_id' => 119,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR //  JUZG. SEGUNDO CIVIL MCPAL // RAD. 2019-1065 // 07/10/2019 // MEDIDA CAUTELAR 50% DE LOS INGRESOS // NOTIF. KM 12 VIA CERRITO LA PALMIRA VALLE INGENIO PROVIDENCIA S,A',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-08 09:08:13',
                'updated_at' => '2019-10-08 09:08:13',
            ),
            127 => 
            array (
                'id' => 128,
                'proceso_id' => 120,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR // JUZG. SEGUNDO CIVIL MCPAL // RAD. 2019-1066 // 07/10/2019 // MEDIDA CAUTELAR 50% DE LOS INGRESOS // NOTIF. DIAGONAL 25 No. 9-26 SOACHA CUNDINAMARCA //',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-10-08 09:13:47',
                'updated_at' => '2019-10-08 09:13:47',
            ),
            128 => 
            array (
                'id' => 129,
                'proceso_id' => 89,
                'fecha_anotacion' => NULL,
                'asunto' => '',
                'descripcion' => '',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 8,
                'user_update_id' => 0,
                'created_at' => '2019-10-30 16:03:36',
                'updated_at' => '2019-10-30 16:03:36',
            ),
            129 => 
            array (
                'id' => 130,
                'proceso_id' => 28,
                'fecha_anotacion' => NULL,
                'asunto' => 'TERMINACIÓN DEL PROCESO',
                'descripcion' => '',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 8,
                'user_update_id' => 0,
                'created_at' => '2019-10-30 17:03:01',
                'updated_at' => '2019-10-30 17:03:01',
            ),
            130 => 
            array (
                'id' => 131,
                'proceso_id' => 121,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA ',
                'descripcion' => 'SE RADICÓ DEMANDA DEL TITULAR // JUZGADO SÉPTIMO CIVIL MUNICIPAL // 14/11/2019 // RADICADO 2019-1187',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-11-15 12:00:02',
                'updated_at' => '2019-11-15 12:00:02',
            ),
            131 => 
            array (
                'id' => 132,
                'proceso_id' => 122,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL CODEUDOR DEL CRÉDITO // JUZGADO TERCERO CIVIL MUNICIPAL // RAD 2019-1215 // 14-11-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-11-15 12:02:03',
                'updated_at' => '2019-11-15 12:02:03',
            ),
            132 => 
            array (
                'id' => 133,
                'proceso_id' => 123,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR DEL CRÉDITO JUZGADO SEXTO CIVIL MUNICIPAL // RAD 2019-1218 // 14-11-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-11-15 12:04:10',
                'updated_at' => '2019-11-15 12:04:10',
            ),
            133 => 
            array (
                'id' => 134,
                'proceso_id' => 124,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR DEL CRÉDITO JUZG. CUARTO CIVIL MPAL // RAD 2019-1185 // 14-11-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-11-15 12:12:36',
                'updated_at' => '2019-11-15 12:12:36',
            ),
            134 => 
            array (
                'id' => 135,
                'proceso_id' => 125,
                'fecha_anotacion' => NULL,
                'asunto' => 'DEMANDA',
                'descripcion' => 'SE RADICÓ DEMANDA AL TITULAR DEL CRÉDITO JUZG. OCTAVO CIVIL MPAL // RAD 2019-1167 // 14-11-2019',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 137,
                'user_update_id' => 0,
                'created_at' => '2019-11-15 12:14:23',
                'updated_at' => '2019-11-15 12:14:23',
            ),
            135 => 
            array (
                'id' => 136,
                'proceso_id' => 126,
                'fecha_anotacion' => NULL,
                'asunto' => '',
                'descripcion' => '',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-11-18 12:20:26',
                'updated_at' => '2019-11-18 12:20:26',
            ),
            136 => 
            array (
                'id' => 137,
                'proceso_id' => 127,
                'fecha_anotacion' => NULL,
                'asunto' => '',
                'descripcion' => '',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 118,
                'user_update_id' => 0,
                'created_at' => '2019-12-12 10:35:34',
                'updated_at' => '2019-12-12 10:35:34',
            ),
            137 => 
            array (
                'id' => 138,
                'proceso_id' => 109,
                'fecha_anotacion' => NULL,
                'asunto' => 'TERMINACIÒN',
                'descripcion' => 'Se realiza un acuerdo y se le da terminado el proceso y paga cuotas mensuales de 200.000, esta en Palmira en una fundaciòn',
                'recordatorio' => '0000-00-00',
                'notificado' => 'No',
                'user_create_id' => 8,
                'user_update_id' => 0,
                'created_at' => '2019-12-13 07:53:01',
                'updated_at' => '2019-12-13 07:53:01',
            ),
        ));
        
        
    }
}
