<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert([
            [
                'id' => 1,
                'name' => 'simular',
                'display_name' => 'Simulador',
                'description' => 'Permite calcular el valor de la cuota',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Simulador',
            ],
            [
                'id' => 2,
                'name' => 'consultar_clientes',
                'display_name' => 'Consultar clientes',
                'description' => 'Permite listar y ver la informacin detallada de los clientes',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Clientes',
            ],
            [
                'id' => 3,
                'name' => 'crear_clientes',
                'display_name' => 'Crear cliente',
                'description' => 'Permite crear clientes',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Clientes',
            ],
            [
                'id' => 4,
                'name' => 'editar_clientes',
                'display_name' => 'Editar cliente',
                'description' => 'Permite editar los clientes',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Clientes',
            ],
            [
                'id' => 5,
                'name' => 'eliminar_clientes',
                'display_name' => 'Eliminar clientes',
                'description' => 'Permite eliminar los clientes',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Clientes',
            ],
            [
                'id' => 6,
                'name' => 'crear_editar_oficios',
                'display_name' => 'Crear y editar oficios',
                'description' => 'Permite crear y editar los oficios que se asignan a los clientes',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Oficios',
            ],
            [
                'id' => 7,
                'name' => 'eliminar_oficios',
                'display_name' => 'Eliminar oficios',
                'description' => 'Permite eliminar un oficio',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Oficios',
            ],
            [
                'id' => 8,
                'name' => 'borrar_documentos',
                'display_name' => 'Borrar documentacion',
                'description' => 'Permite borrar documentos del cliente',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Clientes',
            ],
            [
                'id' => 9,
                'name' => 'exportar_todo',
                'display_name' => 'Exportar todos clientes',
                'description' => 'Permite exportar todos los archivos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'CallCenter',
            ],
            [
                'id' => 10,
                'name' => 'exportar_sucursal',
                'display_name' => 'Exportar clientes por sucursal',
                'description' => 'Permite exportar todos los creditos por sucursal',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'CallCenter',
            ],
            [
                'id' => 11,
                'name' => 'consultar',
                'display_name' => 'Consultar todos los listados',
                'description' => 'Permite listar todos los creditos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'CallCenter',
            ],
            [
                'id' => 12,
                'name' => 'registro_llamada',
                'display_name' => 'Registro de llamada',
                'description' => 'Permite registrar llamadas CallCenter',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'CallCenter',
            ],
            [
                'id' => 13,
                'name' => 'consultar_creditos',
                'display_name' => 'Consultar creditos',
                'description' => 'Permite listar y ver los creditos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 14,
                'name' => 'crear_creditos',
                'display_name' => 'Crear crédito',
                'description' => 'Permite crear crditos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 15,
                'name' => 'ver_seguimiento_proceso_prejuridico',
                'display_name' => 'Consultar el seguimeinto a un proceso pre/jurdico',
                'description' => 'Permite consultar el seguimeinto a un proceso pre/jurdico',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pre/Juridicos',
            ],
            [
                'id' => 16,
                'name' => 'crear_seguimiento_proceso_prejuridico',
                'display_name' => 'Crear el seguimeinto a un proceso pre/jurdico',
                'description' => 'Permite crear el seguimeinto a un proceso pre/jurdico',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pre/Juridicos',
            ],
            [
                'id' => 17,
                'name' => 'editar_creditos',
                'display_name' => 'Editar credito',
                'description' => 'Permite editar la informacion del credito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 18,
                'name' => 'eliminar_credito',
                'display_name' => 'Eliminar credito',
                'description' => 'Permite eliminar el credito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 19,
                'name' => 'refinanciar_creditos',
                'display_name' => 'Refinanciar credito',
                'description' => 'Permite listar y refinanciar los creditos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 20,
                'name' => 'exportar_creditos',
                'display_name' => 'Exportar todos los creditos',
                'description' => 'Permite exportar rodos los creditos xls',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 21,
                'name' => 'llamar_creditos',
                'display_name' => 'Llamar credito',
                'description' => 'Permite registrar llamada al cliente relacionado al crdito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 22,
                'name' => 'consultar_solicitudes',
                'display_name' => 'Consultar solicitud',
                'description' => 'Permite listar y ver solicitudes de crdito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Solicitudes',
            ],
            [
                'id' => 23,
                'name' => 'crear_solicitudes',
                'display_name' => 'Crear solicitud',
                'description' => 'Permite crear varias solicitudes a un mismo cliente',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Solicitudes',
            ],
            [
                'id' => 24,
                'name' => 'editar_solicitudes',
                'display_name' => 'Editar solicitud',
                'description' => 'Permite editar la solicitud',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Solicitudes',
            ],
            [
                'id' => 25,
                'name' => 'editar_producto_solicitudes',
                'display_name' => 'Editar producto de solicitud',
                'description' => 'Permite editar el producto asignado a la solicitud',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Solicitudes',
            ],
            [
                'id' => 26,
                'name' => 'aprobar_solicitudes',
                'display_name' => 'Aprobar solicitudes',
                'description' => 'Permite cambiar el estado de la solicitud a aprobado, negado, cliente  desisti, etc',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Solicitudes',
            ],
            [
                'id' => 27,
                'name' => 'valores_iniciales',
                'display_name' => 'Registrar pago a solicitud',
                'description' => 'Permite realizar los pagos a una solicitud de crdito como iniciales y estudios',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Solicitudes',
            ],
            [
                'id' => 28,
                'name' => 'anular_pago_solicitud',
                'display_name' => 'Anular pago de Solicitud',
                'description' => 'Permite anular el pago realizado a una Solicitud',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Solicitudes',
            ],
            [
                'id' => 29,
                'name' => 'exportar_solicitudes',
                'display_name' => 'Exportar',
                'description' => 'Permite exportar todas las solicitudes',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Solicitudes',
            ],
            [
                'id' => 30,
                'name' => 'consultar_cancelados',
                'display_name' => 'Consultar créditos cancelados',
                'description' => 'Permite listar y consultar los crditos cancelados',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Cancelados',
            ],
            [
                'id' => 31,
                'name' => 'consultar_sanciones',
                'display_name' => 'Consultar Sanciones',
                'description' => 'Permite consultar sanciones diarias',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Sanciones',
            ],
            [
                'id' => 32,
                'name' => 'gestionar_sanciones',
                'display_name' => 'Gestionar Sanciones',
                'description' => 'Permite crear y exonerar sanciones diarias',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Sanciones',
            ],
            [
                'id' => 33,
                'name' => 'consultar_estudio',
                'display_name' => 'Consultar Estudio',
                'description' => 'Permite consultar estudio del cliente',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Estudio',
            ],
            [
                'id' => 34,
                'name' => 'crear_estudios',
                'display_name' => 'Crear estudio',
                'description' => 'Permite crear y editar un estudio de crdito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Estudio',
            ],
            [
                'id' => 35,
                'name' => 'crear_referencias',
                'display_name' => 'Crear referencias',
                'description' => 'Permite crear y editar referencias del cliente',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Estudio',
            ],
            [
                'id' => 36,
                'name' => 'registrar_otros_ingresos',
                'display_name' => 'Registrar otros ingresos',
                'description' => 'Permite agregar el pago o abono de otros ingresos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Otros ingresos',
            ],
            [
                'id' => 37,
                'name' => 'hacer_pago',
                'display_name' => 'Hacer pago de credito',
                'description' => 'Permite crear el pago o abono de un credito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pago credito',
            ],
            [
                'id' => 38,
                'name' => 'ver_pagos_credito',
                'display_name' => 'Consultar el pago de un recibo',
                'description' => 'Permite ver el pago o abono de un credito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pago credito',
            ],
            [
                'id' => 39,
                'name' => 'imprimir_pago_credito',
                'display_name' => 'Imprimir recibo de pago de un credito',
                'description' => 'Permite imprimir pago o abono de un credito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pago credito',
            ],
            [
                'id' => 40,
                'name' => 'anular_pago_credito',
                'display_name' => 'Anular pago de un credito',
                'description' => 'Permite anular el recibo de un pago o abono de un credito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pago credito',
            ],
            [
                'id' => 41,
                'name' => 'listar_pagos_anulados',
                'display_name' => 'Listar pago creditos anulados',
                'description' => 'Permite listar el pago o abono de un credito anulado',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pago credito',
            ],
            [
                'id' => 42,
                'name' => 'pagos_masivos',
                'display_name' => 'Cargar archivo de pagos masivos',
                'description' => 'Permite cargar archivo de pagos masivos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pago credito',
            ],
            [
                'id' => 43,
                'name' => 'consultar_egresos',
                'display_name' => 'Consultar Egresos',
                'description' => 'Permite consultar egresos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Egresos',
            ],
            [
                'id' => 44,
                'name' => 'crear_egresos',
                'display_name' => 'Crear Egresos',
                'description' => 'Permite crear egresos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Egresos',
            ],
            [
                'id' => 45,
                'name' => 'eliminar_egresos',
                'display_name' => 'Eliminar Egresos',
                'description' => 'Permite eliminar egresos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Egresos',
            ],
            [
                'id' => 46,
                'name' => 'exportar_egresos',
                'display_name' => 'Exportar Egresos',
                'description' => 'Permite exportar egresos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Egresos',
            ],
            [
                'id' => 47,
                'name' => 'ver_proveedores',
                'display_name' => 'Ver Proveedores',
                'description' => 'Permite ver proveedores',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Egresos',
            ],
            [
                'id' => 48,
                'name' => 'crear_proveedor',
                'display_name' => 'Crear Proveedor',
                'description' => 'Permite crear proveedor',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Egresos',
            ],
            [
                'id' => 49,
                'name' => 'editar_proveedor',
                'display_name' => 'Editar Proveedor',
                'description' => 'Permite editar proveedor',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Egresos',
            ],
            [
                'id' => 50,
                'name' => 'consultar_multas',
                'display_name' => 'Consultar Pre/Juridicos',
                'description' => 'Permite consultar y listar multas por Prejurdicos y Juridicos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pre/Juridicos',
            ],
            [
                'id' => 51,
                'name' => 'exportar_PreJuridicos',
                'display_name' => 'Exportar Pre/Juridicos',
                'description' => 'Permite exportar Pre/Juridicos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pre/Juridicos',
            ],
            [
                'id' => 52,
                'name' => 'editar_PreJuridicos',
                'display_name' => 'Editar Pre/Juridicos',
                'description' => 'Permite editar Pre/Juridicos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pre/Juridicos',
            ],
            [
                'id' => 53,
                'name' => 'crear_PreJuridicos',
                'display_name' => 'Crear Pre/Juridicos',
                'description' => 'Permite crear Pre/Juridicos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Pre/Juridicos',
            ],
            [
                'id' => 54,
                'name' => 'generar_reporte',
                'display_name' => 'Genera todos los reportes',
                'description' => 'Permite generar todos los reportes administrativos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 55,
                'name' => 'auditoria_sistema',
                'display_name' => 'Auditoria del Sistema',
                'description' => 'Permite generar reporte para Auditoria del Sistema',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 56,
                'name' => 'ver_caja',
                'display_name' => 'Ver Caja',
                'description' => 'Permite ver caja',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 57,
                'name' => 'cartera_castigada',
                'display_name' => 'Cartera Castigada',
                'description' => 'Permite generar reporte para Cartera Castigada',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 58,
                'name' => 'call_center',
                'display_name' => 'Call Center',
                'description' => 'Permite generar reporte para Call Center',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 59,
                'name' => 'egresos',
                'display_name' => 'Egresos',
                'description' => 'Permite generar reporte para Egresos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Contabilidad',
            ],
            [
                'id' => 60,
                'name' => 'financiero_operativo',
                'display_name' => 'Financiero operativo',
                'description' => 'Permite generar reporte para Financiero operativo',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 61,
                'name' => 'general',
                'display_name' => 'General',
                'description' => 'Permite generar reporte para General',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 62,
                'name' => 'general_carteras',
                'display_name' => 'General por Carteras',
                'description' => 'Permite generar reporte para General por Carteras',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 63,
                'name' => 'general_funcionario',
                'display_name' => 'General por Funcionario',
                'description' => 'Permite generar reporte para General por Funcionario',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 64,
                'name' => 'historial_venta_creditos',
                'display_name' => 'Historial Venta de Creditos',
                'description' => 'Permite generar reporte para Historial Venta de Creditos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 65,
                'name' => 'informe_carteras',
                'display_name' => 'Informe Cartera',
                'description' => 'Permite generar reporte para Informe Cartera',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 66,
                'name' => 'morosos',
                'display_name' => 'Morosos',
                'description' => 'Permite generar reporte para Morosos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 67,
                'name' => 'reporte_datacredito',
                'display_name' => 'Reporte Datacredito',
                'description' => 'Permite generar reporte para Reporte Datacredito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 68,
                'name' => 'reporte_procredito',
                'display_name' => 'Reporte procredito',
                'description' => 'Permite generar reporte para procredito',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 69,
                'name' => 'reporte_datacredito_asistimotos',
                'display_name' => 'Reporte Datacredito Asistimotos',
                'description' => 'Permite generar reporte para Reporte Datacredito Asistimotos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 70,
                'name' => 'venta_creditos',
                'display_name' => 'Venta de Creditos',
                'description' => 'Permite generar reporte para Venta de Creditos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 71,
                'name' => 'venta_credito_asesor',
                'display_name' => 'Venta de Creditos por Asesor',
                'description' => 'Permite generar reporte para Venta de Creditos por Asesor',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Reportes',
            ],
            [
                'id' => 72,
                'name' => 'informes_cartera',
                'display_name' => 'Pantalla informes cartera',
                'description' => 'Permite entrar a la pantalla de Informes por Carteras',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Cartera',
            ],
            [
                'id' => 73,
                'name' => 'repote_por_carteras',
                'display_name' => 'Reporte por carteras',
                'description' => 'Permite ver los saldos de cartera',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Cartera',
            ],
            [
                'id' => 74,
                'name' => 'informe_total_por_puntos',
                'display_name' => 'Informe total por puntos',
                'description' => 'Permite ver Informe Total por Puntos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Cartera',
            ],
            [
                'id' => 75,
                'name' => 'flujo_cajas',
                'display_name' => 'Flujo de Caja',
                'description' => 'Muestra el flujo de caja segun un rango de fechas y la cartera',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Cartera',
            ],
            [
                'id' => 76,
                'name' => 'financiero',
                'display_name' => 'Informe financiero por carteras o negocios',
                'description' => 'Permite consultar el estado financiero de una cartera o varias carteras',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Financiero',
            ],
            [
                'id' => 77,
                'name' => 'consultar_negocios',
                'display_name' => 'Consultar  Negocios',
            'description' => 'Permite ver o listar negocios (agrupacin de carteras)',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Negocios',
            ],
            [
                'id' => 78,
                'name' => 'crear_negocios',
                'display_name' => 'Crear Negocios',
                'description' => 'Permite crear Negocios',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Negocios',
            ],
            [
                'id' => 79,
                'name' => 'editar_negocios',
                'display_name' => 'Editar Negocios',
                'description' => 'Permite editar Negocios',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Negocios',
            ],
            [
                'id' => 80,
                'name' => 'eliminar_negocios',
                'display_name' => 'Eliminar Negocios',
                'description' => 'Permite eliminar Negocios',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Negocios',
            ],
            [
                'id' => 81,
                'name' => 'consultar_carteras',
                'display_name' => 'Consultar carteras',
                'description' => 'Permite listar y consultar carteras',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Carteras',
            ],
            [
                'id' => 82,
                'name' => 'crear_carteras',
                'display_name' => 'Crear carteras',
                'description' => 'Permite crear carteras',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Carteras',
            ],
            [
                'id' => 83,
                'name' => 'editar_carteras',
                'display_name' => 'Editar carteras',
                'description' => 'Permite editar carteras',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Carteras',
            ],
            [
                'id' => 84,
                'name' => 'eliminar_carteras',
                'display_name' => 'Eliminar carteras',
                'description' => 'Permite eliminar carteras',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Carteras',
            ],
            [
                'id' => 85,
                'name' => 'consultar_users',
                'display_name' => 'Consultar usuarios del sistema',
                'description' => 'Permite listar y ver los usuarios del sistema',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Users',
            ],
            [
                'id' => 86,
                'name' => 'crear_users',
                'display_name' => 'Crear usuario del sistema',
                'description' => 'Permite crear usuario del sistema',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Users',
            ],
            [
                'id' => 87,
                'name' => 'editar_users',
                'display_name' => 'Editar usuario del sistema',
                'description' => 'Permite editar usuarios del sistema',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Users',
            ],
            [
                'id' => 88,
                'name' => 'eliminar_users',
                'display_name' => 'Eliminar usuarios del sistema',
                'description' => 'Permite eliminar usuarios del sistema',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Users',
            ],
            [
                'id' => 89,
                'name' => 'consultar_permisos',
                'display_name' => 'Consultar roles y permisos',
                'description' => 'Permite consultar los roles y permisos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Rol/Permisos',
            ],
            [
                'id' => 90,
                'name' => 'modificar_permisos',
                'display_name' => 'Crear y modificar roles y permisos',
                'description' => 'Permite, modificar y eliminar roles y permisos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Rol/Permisos',
            ],
            [
                'id' => 91,
                'name' => 'consultar_puntos',
                'display_name' => 'Consultar puntos',
                'description' => 'Permite consultar y listar puntos o sucursales',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Puntos',
            ],
            [
                'id' => 92,
                'name' => 'crear_puntos',
                'display_name' => 'Crear Puntos',
                'description' => 'Permite crear Puntos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Puntos',
            ],
            [
                'id' => 93,
                'name' => 'editar_puntos',
                'display_name' => 'Editar Puntos',
                'description' => 'Permite editar Puntos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Puntos',
            ],
            [
                'id' => 94,
                'name' => 'eliminar_puntos',
                'display_name' => 'Eliminar Puntos',
                'description' => 'Permite eliminar Puntos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Puntos',
            ],
            [
                'id' => 95,
                'name' => 'crear_producto',
                'display_name' => 'Crear Productos',
                'description' => 'Permite crear Productos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Productos',
            ],
            [
                'id' => 96,
                'name' => 'consultar_productos',
                'display_name' => 'Consultar y listar productos',
                'description' => 'Permite consultar y listar productos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Productos',
            ],
            [
                'id' => 97,
                'name' => 'editar_productos',
                'display_name' => 'Editar Productos',
                'description' => 'Permite editar Productos',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Productos',
            ],
            [
                'id' => 98,
                'name' => 'ver_variables',
                'display_name' => 'Ver Variables',
                'description' => 'Permite ver Variables',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Variables',
            ],
            [
                'id' => 99,
                'name' => 'editar_variables',
                'display_name' => 'Editar Variables',
                'description' => 'Permite editar Variables',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Variables',
            ],
            [
                'id' => 100,
                'name' => 'crear_criteriocall',
                'display_name' => 'Crear Criterios de llamada',
                'description' => 'Permite crear Criterios de llamada',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Criterios de llamada',
            ],
            [
                'id' => 101,
                'name' => 'consultar_criteriocall',
                'display_name' => 'Consultar Criterios de llamada',
                'description' => 'Permite consultar criterios de llamada',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Criterios de llamada',
            ],
            [
                'id' => 102,
                'name' => 'editar_criteriocall',
                'display_name' => 'Editar Criterios de llamada',
                'description' => 'Permite editar criterios de llamada',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Criterios de llamada',
            ],
            [
                'id' => 103,
                'name' => 'eliminar_criteriocall',
                'display_name' => 'Eliminar criterios de llamada',
                'description' => 'Permite eliminar criterios de llamada',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Criterios de llamada',
            ],
            [
                'id' => 104,
                'name' => 'consultar_zonas',
                'display_name' => 'Consultar las zonas',
                'description' => 'Permiste consultar las todas zonas',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Zonas',
            ],
            [
                'id' => 105,
                'name' => 'crear_zonas',
                'display_name' => 'Crea una zona',
                'description' => 'Permiste crear una zona',
                'created_at' => '2020-09-26 19:39:44',
                'updated_at' => '2020-09-26 19:39:44',
                'status' => 'Activo',
                'created_by' => 1,
                'updated_by' => NULL,
                'category' => 'Zonas',
            ],
            [
                'id' => 316,
                'name' => 'subir_documentos',
                'display_name' => 'Subir documentos',
                'description' => 'Permite subir documentos al repositorio de archivos',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 'Activo',
                'created_by' => 2,
                'updated_by' => NULL,
                'category' => 'Clientes',
            ],
            [
                'id' => 317,
                'name' => 'expedir_pazysalvo',
                'display_name' => 'Expedir paz y salvo',
                'description' => 'Genera un certificado de paz y salvo de un crédito para cliente o codeudor',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 'Activo',
                'created_by' => 2,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 318,
                'name' => 'consultar_documento',
                'display_name' => 'Consultar documento',
                'description' => 'Permite ver un documento adjunto a un cliente',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 'Activo',
                'created_by' => 2,
                'updated_by' => NULL,
                'category' => 'Clientes',
            ],
            [
                'id' => 319,
                'name' => 'crear_acuerdo',
                'display_name' => 'Crear acuerdo de pago',
                'description' => 'Permite crear acuerdos de pago con los clientes',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 'Activo',
                'created_by' => 2,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 320,
                'name' => 'editar_acuerdo',
                'display_name' => 'Editar acuerdo de pago',
                'description' => 'Permite editar acuerdos de pago con los clientes',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 'Activo',
                'created_by' => 2,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 321,
                'name' => 'eliminar_acuerdo',
                'display_name' => 'Eliminar acuerdo de pago',
                'description' => 'Permite eliminar acuerdos de pago con los clientes',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 'Activo',
                'created_by' => 2,
                'updated_by' => NULL,
                'category' => 'Creditos',
            ],
            [
                'id' => 322,
                'name' => 'reporte_contable',
                'display_name' => 'Genera reportes contables',
                'description' => 'Permite generar reportes contables',
                'created_at' => NULL,
                'updated_at' => NULL,
                'status' => 'Activo',
                'created_by' => 2,
                'updated_by' => NULL,
                'category' => 'Contabilidad',
            ]
        ]);
    }
}
