<?php

use Illuminate\Database\Seeder;

class ProcesosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('procesos')->delete();
        
        \DB::table('procesos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'juzgado' => 'Nuevo',
                'radicado' => '382957298',
                'fecha_radicado' => '2019-07-22',
                'credito_id' => 4777,
                'cliente_id' => 3990,
                'user_create_id' => 2,
                'user_update_id' => 2,
                'created_at' => '2019-07-22',
                'updated_at' => '2019-07-22',
            ),
            1 => 
            array (
                'id' => 2,
                'juzgado' => 'JUZGADO PRIMERO CIVIL MUNICIPAL',
                'radicado' => '2016-926',
                'fecha_radicado' => '2016-11-11',
                'credito_id' => 2567,
                'cliente_id' => 2253,
                'user_create_id' => 109,
                'user_update_id' => 118,
                'created_at' => '2019-08-12',
                'updated_at' => '2019-08-23',
            ),
            2 => 
            array (
                'id' => 3,
                'juzgado' => 'JUZGADO PRIMERO CIVIL MUNICIPAL',
                'radicado' => '20019-368',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 3674,
                'cliente_id' => 3982,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            3 => 
            array (
                'id' => 4,
                'juzgado' => 'JUZGADO PRIMERO CIVIL MUNICIPAL',
                'radicado' => '2019-512',
                'fecha_radicado' => '2019-05-24',
                'credito_id' => 4355,
                'cliente_id' => 4676,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            4 => 
            array (
                'id' => 5,
                'juzgado' => 'JUZGADO PRIMERO CIVIL MUNICIPAL',
                'radicado' => '2019-526',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 3181,
                'cliente_id' => 3360,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            5 => 
            array (
                'id' => 6,
                'juzgado' => 'JUZGADO PRIMERO CIVIL MUNICIPAL ',
                'radicado' => '2019-518',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 5551,
                'cliente_id' => 6059,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            6 => 
            array (
                'id' => 7,
                'juzgado' => 'PRIMERO CIVIL MUNICIPAL',
                'radicado' => '2019-771',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 2881,
                'cliente_id' => 3094,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            7 => 
            array (
                'id' => 8,
                'juzgado' => 'PRIMERO CIVIL MUNICIPAL ',
                'radicado' => '2019-772',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 696,
                'cliente_id' => 874,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            8 => 
            array (
                'id' => 9,
                'juzgado' => 'PRIMERO CIVIL MUNICIPAL',
                'radicado' => '2019-773',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 4282,
                'cliente_id' => 4618,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            9 => 
            array (
                'id' => 10,
                'juzgado' => 'PRIMERO CIVIL MUNICIPAL',
                'radicado' => '2018-380',
                'fecha_radicado' => '2018-04-18',
                'credito_id' => 1086,
                'cliente_id' => 1241,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            10 => 
            array (
                'id' => 11,
                'juzgado' => 'PRIMERO CIVIL MUNICIPAL ',
                'radicado' => '2018-637',
                'fecha_radicado' => '2018-06-27',
                'credito_id' => 1351,
                'cliente_id' => 1521,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            11 => 
            array (
                'id' => 12,
                'juzgado' => 'PRIMERO CIVIL MUNICIPAL ',
                'radicado' => '2019-370',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 2713,
                'cliente_id' => 447,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            12 => 
            array (
                'id' => 13,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-199',
                'fecha_radicado' => '2019-02-27',
                'credito_id' => 2253,
                'cliente_id' => 2498,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            13 => 
            array (
                'id' => 14,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-340',
                'fecha_radicado' => '2019-04-03',
                'credito_id' => 3954,
                'cliente_id' => 4243,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            14 => 
            array (
                'id' => 15,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-369',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 4058,
                'cliente_id' => 4275,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            15 => 
            array (
                'id' => 16,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-367',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 2384,
                'cliente_id' => 2650,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            16 => 
            array (
                'id' => 17,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL ',
                'radicado' => '2019-519',
                'fecha_radicado' => '2019-05-24',
                'credito_id' => 5933,
                'cliente_id' => 1932,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            17 => 
            array (
                'id' => 18,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL ',
                'radicado' => '2019-558',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 541,
                'cliente_id' => 713,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            18 => 
            array (
                'id' => 19,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-559',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 3282,
                'cliente_id' => 3531,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            19 => 
            array (
                'id' => 20,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-557',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 3743,
                'cliente_id' => 4085,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            20 => 
            array (
                'id' => 21,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-784',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 2759,
                'cliente_id' => 2987,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-24',
                'updated_at' => '2019-08-24',
            ),
            21 => 
            array (
                'id' => 22,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-372',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 4299,
                'cliente_id' => 4628,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-27',
                'updated_at' => '2019-08-27',
            ),
            22 => 
            array (
                'id' => 23,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-519',
                'fecha_radicado' => '2019-05-24',
                'credito_id' => 4137,
                'cliente_id' => 1913,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-27',
                'updated_at' => '2019-08-27',
            ),
            23 => 
            array (
                'id' => 24,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-518',
                'fecha_radicado' => '2019-05-24',
                'credito_id' => 852,
                'cliente_id' => 1032,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-08-27',
                'updated_at' => '2019-08-27',
            ),
            24 => 
            array (
                'id' => 25,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-539',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 1509,
                'cliente_id' => 100,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            25 => 
            array (
                'id' => 26,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2016-997',
                'fecha_radicado' => '2016-12-05',
                'credito_id' => 730,
                'cliente_id' => 908,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            26 => 
            array (
                'id' => 27,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-719',
                'fecha_radicado' => '2019-11-07',
                'credito_id' => 520,
                'cliente_id' => 681,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            27 => 
            array (
                'id' => 28,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-790',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 3174,
                'cliente_id' => 3429,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            28 => 
            array (
                'id' => 29,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-788',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 4497,
                'cliente_id' => 4811,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            29 => 
            array (
                'id' => 30,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-789',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 3360,
                'cliente_id' => 3618,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            30 => 
            array (
                'id' => 31,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2017-215',
                'fecha_radicado' => '0001-02-28',
                'credito_id' => 1400,
                'cliente_id' => 1591,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            31 => 
            array (
                'id' => 32,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2017-895',
                'fecha_radicado' => '2017-08-22',
                'credito_id' => 1092,
                'cliente_id' => 1247,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            32 => 
            array (
                'id' => 33,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2018-716',
                'fecha_radicado' => '2018-07-13',
                'credito_id' => 1369,
                'cliente_id' => 1537,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            33 => 
            array (
                'id' => 34,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2018-636',
                'fecha_radicado' => '2018-06-26',
                'credito_id' => 1735,
                'cliente_id' => 1935,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            34 => 
            array (
                'id' => 35,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-371',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 6448,
                'cliente_id' => 315,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            35 => 
            array (
                'id' => 36,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2018-632',
                'fecha_radicado' => '2018-06-27',
                'credito_id' => 248,
                'cliente_id' => 319,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            36 => 
            array (
                'id' => 37,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-277',
                'fecha_radicado' => '2019-03-14',
                'credito_id' => 4835,
                'cliente_id' => 5162,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            37 => 
            array (
                'id' => 38,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-373',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 3972,
                'cliente_id' => 4264,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            38 => 
            array (
                'id' => 39,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-374',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 4643,
                'cliente_id' => 4941,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            39 => 
            array (
                'id' => 40,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-375',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 2126,
                'cliente_id' => 1332,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            40 => 
            array (
                'id' => 41,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-505',
                'fecha_radicado' => '2019-05-20',
                'credito_id' => 2444,
                'cliente_id' => 2728,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            41 => 
            array (
                'id' => 42,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-516',
                'fecha_radicado' => '2019-05-20',
                'credito_id' => 4465,
                'cliente_id' => 4759,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            42 => 
            array (
                'id' => 43,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-561',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 546,
                'cliente_id' => 718,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            43 => 
            array (
                'id' => 44,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-560',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 4482,
                'cliente_id' => 4875,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            44 => 
            array (
                'id' => 45,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-775',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 2906,
                'cliente_id' => 3148,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            45 => 
            array (
                'id' => 46,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-776',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 3377,
                'cliente_id' => 3576,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            46 => 
            array (
                'id' => 47,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2017-904',
                'fecha_radicado' => '2017-08-24',
                'credito_id' => 1213,
                'cliente_id' => 1368,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            47 => 
            array (
                'id' => 48,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-129',
                'fecha_radicado' => '2019-02-05',
                'credito_id' => 2088,
                'cliente_id' => 2322,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            48 => 
            array (
                'id' => 49,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2018-1109',
                'fecha_radicado' => '2019-02-05',
                'credito_id' => 780,
                'cliente_id' => 963,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            49 => 
            array (
                'id' => 50,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2018-634',
                'fecha_radicado' => '2018-06-27',
                'credito_id' => 2132,
                'cliente_id' => 1017,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            50 => 
            array (
                'id' => 51,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2018-644',
                'fecha_radicado' => '2018-06-29',
                'credito_id' => 560,
                'cliente_id' => 742,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            51 => 
            array (
                'id' => 52,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-379',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 4283,
                'cliente_id' => 4587,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            52 => 
            array (
                'id' => 53,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-380',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 4654,
                'cliente_id' => 4964,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            53 => 
            array (
                'id' => 54,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-516',
                'fecha_radicado' => '2019-05-22',
                'credito_id' => 767,
                'cliente_id' => 940,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            54 => 
            array (
                'id' => 55,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-527',
                'fecha_radicado' => '2019-05-24',
                'credito_id' => 3619,
                'cliente_id' => 3892,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            55 => 
            array (
                'id' => 56,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-542',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 3031,
                'cliente_id' => 3245,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            56 => 
            array (
                'id' => 57,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-575',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 770,
                'cliente_id' => 944,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            57 => 
            array (
                'id' => 58,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-574',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 2263,
                'cliente_id' => 2493,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-11',
                'updated_at' => '2019-09-11',
            ),
            58 => 
            array (
                'id' => 59,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-724',
                'fecha_radicado' => '2019-07-11',
                'credito_id' => 3774,
                'cliente_id' => 4050,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            59 => 
            array (
                'id' => 60,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-797',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 4053,
                'cliente_id' => 4286,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            60 => 
            array (
                'id' => 61,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-798',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 535,
                'cliente_id' => 707,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            61 => 
            array (
                'id' => 62,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2018-654',
                'fecha_radicado' => '2018-06-27',
                'credito_id' => 542,
                'cliente_id' => 714,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            62 => 
            array (
                'id' => 63,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-206',
                'fecha_radicado' => '2019-02-28',
                'credito_id' => 4074,
                'cliente_id' => 4337,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            63 => 
            array (
                'id' => 64,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-347',
                'fecha_radicado' => '2019-04-03',
                'credito_id' => 3335,
                'cliente_id' => 3573,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            64 => 
            array (
                'id' => 65,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-371',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 2247,
                'cliente_id' => 2467,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            65 => 
            array (
                'id' => 66,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-372',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 3281,
                'cliente_id' => 3526,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            66 => 
            array (
                'id' => 67,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-514',
                'fecha_radicado' => '2019-05-22',
                'credito_id' => 5720,
                'cliente_id' => 3100,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            67 => 
            array (
                'id' => 68,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-513',
                'fecha_radicado' => '2019-05-22',
                'credito_id' => 1737,
                'cliente_id' => 1994,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            68 => 
            array (
                'id' => 69,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-524',
                'fecha_radicado' => '2019-05-22',
                'credito_id' => 2705,
                'cliente_id' => 2937,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            69 => 
            array (
                'id' => 70,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-542',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 1158,
                'cliente_id' => 1313,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            70 => 
            array (
                'id' => 71,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-531 ',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 1773,
                'cliente_id' => 1188,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            71 => 
            array (
                'id' => 72,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-527',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 5546,
                'cliente_id' => 6003,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            72 => 
            array (
                'id' => 73,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-798',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 3767,
                'cliente_id' => 4062,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            73 => 
            array (
                'id' => 74,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-800',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 760,
                'cliente_id' => 930,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            74 => 
            array (
                'id' => 75,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2018-17',
                'fecha_radicado' => '2018-01-16',
                'credito_id' => 572,
                'cliente_id' => 750,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            75 => 
            array (
                'id' => 76,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2018-381',
                'fecha_radicado' => '2018-04-18',
                'credito_id' => 1299,
                'cliente_id' => 1455,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            76 => 
            array (
                'id' => 77,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2018.379',
                'fecha_radicado' => '2018-04-18',
                'credito_id' => 1938,
                'cliente_id' => 2187,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            77 => 
            array (
                'id' => 78,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2018-690',
                'fecha_radicado' => '2018-07-11',
                'credito_id' => 538,
                'cliente_id' => 710,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            78 => 
            array (
                'id' => 79,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-275',
                'fecha_radicado' => '2019-03-14',
                'credito_id' => 4231,
                'cliente_id' => 4571,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            79 => 
            array (
                'id' => 80,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-345',
                'fecha_radicado' => '2019-04-03',
                'credito_id' => 2964,
                'cliente_id' => 2242,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            80 => 
            array (
                'id' => 81,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-346',
                'fecha_radicado' => '2019-04-30',
                'credito_id' => 4150,
                'cliente_id' => 4445,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            81 => 
            array (
                'id' => 82,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-370',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 3940,
                'cliente_id' => 4203,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            82 => 
            array (
                'id' => 83,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-530',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 2330,
                'cliente_id' => 2552,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            83 => 
            array (
                'id' => 84,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-529',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 2239,
                'cliente_id' => 2557,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            84 => 
            array (
                'id' => 85,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-556',
                'fecha_radicado' => '2019-06-06',
                'credito_id' => 1571,
                'cliente_id' => 1773,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            85 => 
            array (
                'id' => 86,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-756',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 2103,
                'cliente_id' => 2354,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            86 => 
            array (
                'id' => 87,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-755',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 4501,
                'cliente_id' => 1129,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            87 => 
            array (
                'id' => 88,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-347',
                'fecha_radicado' => '2019-04-03',
                'credito_id' => 6431,
                'cliente_id' => 1182,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            88 => 
            array (
                'id' => 89,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-373',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 4206,
                'cliente_id' => 4478,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            89 => 
            array (
                'id' => 90,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-515',
                'fecha_radicado' => '2019-05-24',
                'credito_id' => 2024,
                'cliente_id' => 2231,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            90 => 
            array (
                'id' => 91,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-514',
                'fecha_radicado' => '2019-05-24',
                'credito_id' => 3906,
                'cliente_id' => 4231,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-12',
                'updated_at' => '2019-09-12',
            ),
            91 => 
            array (
                'id' => 92,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-523',
                'fecha_radicado' => '2019-06-03',
                'credito_id' => 8169,
                'cliente_id' => 4017,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            92 => 
            array (
                'id' => 93,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-532',
                'fecha_radicado' => '2019-05-29',
                'credito_id' => 2465,
                'cliente_id' => 2700,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            93 => 
            array (
                'id' => 94,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-779',
                'fecha_radicado' => '2019-07-25',
                'credito_id' => 4092,
                'cliente_id' => 4385,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            94 => 
            array (
                'id' => 95,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2016-713',
                'fecha_radicado' => '0001-09-13',
                'credito_id' => 1282,
                'cliente_id' => 1435,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            95 => 
            array (
                'id' => 96,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-374',
                'fecha_radicado' => '2019-04-09',
                'credito_id' => 752,
                'cliente_id' => 920,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            96 => 
            array (
                'id' => 97,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-506',
                'fecha_radicado' => '2019-05-22',
                'credito_id' => 731,
                'cliente_id' => 909,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            97 => 
            array (
                'id' => 98,
                'juzgado' => 'PRIMERO DE PEQUEÑAS CAUSAS',
                'radicado' => '2018-310',
                'fecha_radicado' => '0001-01-01',
                'credito_id' => 919,
                'cliente_id' => 867,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            98 => 
            array (
                'id' => 99,
                'juzgado' => 'PRIMERO DE PEQUEÑAS CAUSAS',
                'radicado' => '2019-2019',
                'fecha_radicado' => '2019-05-22',
                'credito_id' => 2208,
                'cliente_id' => 1325,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            99 => 
            array (
                'id' => 100,
                'juzgado' => 'PRIMERO DE PEQUEÑAS CAUSAS',
                'radicado' => '20189-284',
                'fecha_radicado' => '2018-06-27',
                'credito_id' => 3398,
                'cliente_id' => 895,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            100 => 
            array (
                'id' => 101,
                'juzgado' => 'SEGUNDO DE PEQUEÑAS CAUSAS',
                'radicado' => '2018-674',
                'fecha_radicado' => '2018-06-26',
                'credito_id' => 2155,
                'cliente_id' => 2434,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            101 => 
            array (
                'id' => 102,
                'juzgado' => 'SEGUNDO DE PEQUEÑAS CAUSAS',
                'radicado' => '2019-352',
                'fecha_radicado' => '2019-04-03',
                'credito_id' => 1058,
                'cliente_id' => 1212,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            102 => 
            array (
                'id' => 103,
                'juzgado' => 'SEGUNDO DE PEQUEÑAS CAUSAS',
                'radicado' => '2016-1233',
                'fecha_radicado' => '0001-08-01',
                'credito_id' => 1466,
                'cliente_id' => 1689,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            103 => 
            array (
                'id' => 104,
                'juzgado' => 'SEGUNDO DE PEQUEÑAS CAUSAS',
                'radicado' => '2015-972',
                'fecha_radicado' => '0001-11-06',
                'credito_id' => 1472,
                'cliente_id' => 1700,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            104 => 
            array (
                'id' => 105,
                'juzgado' => 'SEGUNDO DE PEQUEÑAS CAUSAS',
                'radicado' => '2018-109',
                'fecha_radicado' => '2018-02-02',
                'credito_id' => 81,
                'cliente_id' => 130,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-13',
                'updated_at' => '2019-09-13',
            ),
            105 => 
            array (
                'id' => 106,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-987',
                'fecha_radicado' => '2019-09-17',
                'credito_id' => 3512,
                'cliente_id' => 3788,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-17',
                'updated_at' => '2019-09-17',
            ),
            106 => 
            array (
                'id' => 107,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-986',
                'fecha_radicado' => '2019-09-17',
                'credito_id' => 4252,
                'cliente_id' => 4524,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-18',
                'updated_at' => '2019-09-18',
            ),
            107 => 
            array (
                'id' => 108,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-1003',
                'fecha_radicado' => '2019-09-17',
                'credito_id' => 956,
                'cliente_id' => 1117,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-18',
                'updated_at' => '2019-09-18',
            ),
            108 => 
            array (
                'id' => 109,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL',
                'radicado' => '2019-1015',
                'fecha_radicado' => '2019-09-17',
                'credito_id' => 953,
                'cliente_id' => 1112,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-18',
                'updated_at' => '2019-09-18',
            ),
            109 => 
            array (
                'id' => 110,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-1006',
                'fecha_radicado' => '2019-09-17',
                'credito_id' => 3123,
                'cliente_id' => 140,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-18',
                'updated_at' => '2019-09-18',
            ),
            110 => 
            array (
                'id' => 111,
                'juzgado' => 'PRIMERO CIVIL MUNICIPAL',
                'radicado' => '2019-0980',
                'fecha_radicado' => '2019-09-17',
                'credito_id' => 2786,
                'cliente_id' => 647,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-18',
                'updated_at' => '2019-09-18',
            ),
            111 => 
            array (
                'id' => 112,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-0984',
                'fecha_radicado' => '2019-09-17',
                'credito_id' => 3346,
                'cliente_id' => 1777,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-09-18',
                'updated_at' => '2019-09-18',
            ),
            112 => 
            array (
                'id' => 113,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-1056',
                'fecha_radicado' => '2019-10-07',
                'credito_id' => 3383,
                'cliente_id' => 3568,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-10-07',
                'updated_at' => '2019-10-07',
            ),
            113 => 
            array (
                'id' => 114,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-1055',
                'fecha_radicado' => '2019-10-07',
                'credito_id' => 2456,
                'cliente_id' => 2724,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-10-08',
                'updated_at' => '2019-10-08',
            ),
            114 => 
            array (
                'id' => 115,
                'juzgado' => 'QUINTO CIVIL MUNICIPAL',
                'radicado' => '2019-1075',
                'fecha_radicado' => '2019-10-07',
                'credito_id' => 3469,
                'cliente_id' => 3755,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-10-08',
                'updated_at' => '2019-10-08',
            ),
            115 => 
            array (
                'id' => 116,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-1063',
                'fecha_radicado' => '2019-10-07',
                'credito_id' => 5168,
                'cliente_id' => 5556,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-10-08',
                'updated_at' => '2019-10-08',
            ),
            116 => 
            array (
                'id' => 117,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-1064',
                'fecha_radicado' => '2019-10-07',
                'credito_id' => 1903,
                'cliente_id' => 2066,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-10-08',
                'updated_at' => '2019-10-08',
            ),
            117 => 
            array (
                'id' => 118,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL',
                'radicado' => '2019-1077',
                'fecha_radicado' => '2019-10-07',
                'credito_id' => 1850,
                'cliente_id' => 2042,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-10-08',
                'updated_at' => '2019-10-08',
            ),
            118 => 
            array (
                'id' => 119,
                'juzgado' => 'SEGUNDO CIVIL MUNICIPAL',
                'radicado' => '2019-1065',
                'fecha_radicado' => '2019-10-07',
                'credito_id' => 3864,
                'cliente_id' => 4134,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-10-08',
                'updated_at' => '2019-10-08',
            ),
            119 => 
            array (
                'id' => 120,
                'juzgado' => 'SEGUNDO CIVIL MCPAL',
                'radicado' => '2019-1066',
                'fecha_radicado' => '2019-10-07',
                'credito_id' => 4028,
                'cliente_id' => 4341,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-10-08',
                'updated_at' => '2019-10-08',
            ),
            120 => 
            array (
                'id' => 121,
                'juzgado' => 'SÉPTIMO CIVIL MUNICIPAL',
                'radicado' => '2019-1187',
                'fecha_radicado' => '2019-11-14',
                'credito_id' => 2198,
                'cliente_id' => 2488,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-11-15',
                'updated_at' => '2019-11-15',
            ),
            121 => 
            array (
                'id' => 122,
                'juzgado' => 'TERCERO CIVIL MUNICIPAL ',
                'radicado' => '2019-1215',
                'fecha_radicado' => '2019-11-14',
                'credito_id' => 8767,
                'cliente_id' => 9795,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-11-15',
                'updated_at' => '2019-11-15',
            ),
            122 => 
            array (
                'id' => 123,
                'juzgado' => 'SEXTO CIVIL MUNICIPAL ',
                'radicado' => '2019-1218',
                'fecha_radicado' => '2019-11-14',
                'credito_id' => 3718,
                'cliente_id' => 4054,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-11-15',
                'updated_at' => '2019-11-15',
            ),
            123 => 
            array (
                'id' => 124,
                'juzgado' => 'CUARTO CIVIL MUNICIPAL',
                'radicado' => '2019-1185',
                'fecha_radicado' => '2019-11-14',
                'credito_id' => 7187,
                'cliente_id' => 7470,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-11-15',
                'updated_at' => '2019-11-15',
            ),
            124 => 
            array (
                'id' => 125,
                'juzgado' => 'OCTAVO CIVIL MUNICIPAL',
                'radicado' => '2019-1167',
                'fecha_radicado' => '2019-11-14',
                'credito_id' => 573,
                'cliente_id' => 751,
                'user_create_id' => 137,
                'user_update_id' => NULL,
                'created_at' => '2019-11-15',
                'updated_at' => '2019-11-15',
            ),
            125 => 
            array (
                'id' => 126,
                'juzgado' => 'tercero civil municipal',
                'radicado' => '66001400300320180057800',
                'fecha_radicado' => '2018-12-06',
                'credito_id' => 642,
                'cliente_id' => 823,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-11-18',
                'updated_at' => '2019-11-18',
            ),
            126 => 
            array (
                'id' => 127,
                'juzgado' => 'tercero civil municipal ',
                'radicado' => '66001-40-03-003-2019-001166-00',
                'fecha_radicado' => '2019-11-22',
                'credito_id' => 933,
                'cliente_id' => 1092,
                'user_create_id' => 118,
                'user_update_id' => NULL,
                'created_at' => '2019-12-12',
                'updated_at' => '2019-12-12',
            ),
        ));
        
        
    }
}
