<?php

use Illuminate\Database\Seeder;

class ProveedoresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('proveedores')->delete();
        
        \DB::table('proveedores')->insert(array (
            0 => 
            array (
                'id' => 4,
                'nombre' => 'prueba',
                'estado' => 'Activo',
                'tipo_doc' => 'Cedula Ciudadanía',
                'num_doc' => '1000010000',
                'telefono' => '',
                'direccion' => '',
                'user_create_id' => 2,
                'user_update_id' => NULL,
                'created_at' => '2019-06-03 23:55:42',
                'updated_at' => '2019-06-03 23:55:42',
            ),
            1 => 
            array (
                'id' => 5,
                'nombre' => 'CDA DEL  EJE CAFETERO ',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900352258',
                'telefono' => '3172025',
                'direccion' => 'AV EL POLLO',
                'user_create_id' => 10,
                'user_update_id' => NULL,
                'created_at' => '2019-06-04 15:00:49',
                'updated_at' => '2019-06-04 15:00:49',
            ),
            2 => 
            array (
                'id' => 6,
                'nombre' => 'CERTIFIMOTOS S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '901171384-4',
                'telefono' => '3174420901 - 3108076217',
                'direccion' => 'CALLE 25 # 10-05 LOCOALES 1-2-3 SECTOR LA VIBORA POSTOBON',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 09:38:43',
                'updated_at' => '2019-06-25 09:38:43',
            ),
            3 => 
            array (
                'id' => 7,
                'nombre' => 'FABIO HUMBERTO PEREZ AVENDANO / FIP SEGUROS',
                'estado' => 'Activo',
                'tipo_doc' => 'Cedula Ciudadanía',
                'num_doc' => '93337032',
                'telefono' => '3177289830',
                'direccion' => 'CARRERA 2 # 17-23 LA DORADA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 09:43:54',
                'updated_at' => '2019-06-25 09:43:54',
            ),
            4 => 
            array (
                'id' => 8,
                'nombre' => 'DIDIER ALEXANDER ACEVEDO SERNA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '4514542-1',
                'telefono' => '3113443860',
                'direccion' => 'CARRERA 6 # 17-53 LOCAL 12 CENTRO COMERCIAL LAS FUENTES',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 09:48:11',
                'updated_at' => '2019-06-25 09:48:11',
            ),
            5 => 
            array (
                'id' => 9,
                'nombre' => 'MAXI-MOTOS S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900985985-0',
                'telefono' => '',
                'direccion' => 'BOGOTA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 09:54:27',
                'updated_at' => '2019-06-25 09:54:27',
            ),
            6 => 
            array (
                'id' => 10,
                'nombre' => 'CONTROL MOTOS IBAGUE S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900465828-1',
                'telefono' => '',
                'direccion' => 'IBAGUE',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 09:56:45',
                'updated_at' => '2019-06-25 09:56:45',
            ),
            7 => 
            array (
                'id' => 11,
                'nombre' => 'CENTRO DE DIAGNOSTICO AUTOMOTRIZ TECNI MOTORS QUIMBAYA S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '901026481-0',
                'telefono' => '3203427839',
                'direccion' => 'CALLE 19 CARRERA 7  21 LT - 1',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 10:00:21',
                'updated_at' => '2019-06-25 10:00:21',
            ),
            8 => 
            array (
                'id' => 12,
                'nombre' => 'MOTOS EL GALLINERAL S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '901111721-7',
                'telefono' => '',
                'direccion' => 'SAN GIL',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 10:09:54',
                'updated_at' => '2019-06-25 10:09:54',
            ),
            9 => 
            array (
                'id' => 13,
                'nombre' => 'CAMACHOS ASESORES',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '1075265284-1',
                'telefono' => '3214528765',
                'direccion' => 'CC LOS COMUNEROS OFICINA  3004',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 10:13:54',
                'updated_at' => '2019-06-25 10:13:54',
            ),
            10 => 
            array (
                'id' => 14,
                'nombre' => 'CENTRO DE DIAGNOSTICO AUTOMOTOR LOS PRIMOS S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900994760-9',
                'telefono' => '3208955030',
                'direccion' => 'CALLE 8 # 28A-04',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 10:18:16',
                'updated_at' => '2019-06-25 10:18:16',
            ),
            11 => 
            array (
                'id' => 15,
                'nombre' => 'CENTRO DE DIAGNOSTICO AUTOMOTRIZ MOTO CLUB AMBALA S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900882724-2',
                'telefono' => '3168308917',
                'direccion' => 'AV AMBALA # 26-66',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 10:20:22',
                'updated_at' => '2019-06-25 10:20:22',
            ),
            12 => 
            array (
                'id' => 16,
                'nombre' => 'CENTRO DE DIAGNOSTICO AUTOMOTIRZ TECNI MOTORS IBAGUE',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900987009-6',
                'telefono' => '3203427846',
                'direccion' => 'CARRERA 8 # 139-35 BARRIO CEIBA SALADO',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 10:53:03',
                'updated_at' => '2019-06-25 10:53:03',
            ),
            13 => 
            array (
                'id' => 17,
                'nombre' => 'PAP INVERSIONES LTDA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900216835-6',
                'telefono' => '3167416022',
                'direccion' => 'CARRERA 6 # 20-19/23',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 10:55:36',
                'updated_at' => '2019-06-25 10:55:36',
            ),
            14 => 
            array (
                'id' => 18,
                'nombre' => 'CENTRO DE DIAGNOSTICO AUTOMOTOR CEDIPLUS SOACHA S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '901114227-3',
                'telefono' => '',
                'direccion' => 'CARRERA 4 # 20-84  SOACHA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:02:34',
                'updated_at' => '2019-06-25 11:02:34',
            ),
            15 => 
            array (
                'id' => 19,
                'nombre' => 'CARSEGUROSPEREIRA LTDA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900705911-6',
                'telefono' => '3206483097',
                'direccion' => 'CALLE 19  # 6-4B LOCAL 216 ALCIDES AREVALO',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:05:23',
                'updated_at' => '2019-06-25 11:05:23',
            ),
            16 => 
            array (
                'id' => 20,
                'nombre' => 'MOTO UNION S.A.S ',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900866200-8',
                'telefono' => '3163943596 - 3176451979',
                'direccion' => 'CALLE 14  # 10-69  TULUA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:09:48',
                'updated_at' => '2019-06-25 11:09:48',
            ),
            17 => 
            array (
                'id' => 21,
                'nombre' => 'LIDERES EN ASISTENCIA PROFESIONAL E INTEGRAL EN SERVICIOS DE TRANSITO Y TRANSPORTE AUTOMOTOR S.A.S  LA PISTA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900014037-8',
                'telefono' => '2315318',
                'direccion' => 'CALLE 39  # 28-09',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:15:38',
                'updated_at' => '2019-06-25 11:15:38',
            ),
            18 => 
            array (
                'id' => 22,
                'nombre' => 'CENTRO DE DIAGNOSTICO AUTOMOTRIZ  UNIMOTOS ',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900750755-4',
                'telefono' => '3159254582',
                'direccion' => 'CARRERA 1 D # 15-58 AVENIDA CIRCUNVALAR',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:20:11',
                'updated_at' => '2019-06-25 11:20:11',
            ),
            19 => 
            array (
                'id' => 23,
                'nombre' => 'TEAM ADVANCE S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900327922-5',
                'telefono' => '3176477913',
                'direccion' => 'CARRERA 8 # 9-89 ',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:23:23',
                'updated_at' => '2019-06-25 11:23:23',
            ),
            20 => 
            array (
                'id' => 24,
                'nombre' => 'INSPECCION TECNICA AUTOMOTRIZ INTECO S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900117522-1',
                'telefono' => '5440795',
                'direccion' => 'CALLE 17  # 115-55',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:26:49',
                'updated_at' => '2019-06-25 11:26:49',
            ),
            21 => 
            array (
                'id' => 25,
                'nombre' => 'CENTRO DE ENSE;ANZA AUTOMOVILISTICA CACIQUE TONE S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900750383-8',
                'telefono' => '8502889',
                'direccion' => 'CARRERA 31 # 24-05  URRAO',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:34:00',
                'updated_at' => '2019-06-25 11:34:00',
            ),
            22 => 
            array (
                'id' => 26,
                'nombre' => 'CENTRO DE ENSENANZA AUTOMOVILISTICA CONDUCALDAS T.P S,A,S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900655924-6',
                'telefono' => '3118872727',
                'direccion' => 'CALLE 28 # 10-12',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:36:05',
                'updated_at' => '2019-06-25 11:36:05',
            ),
            23 => 
            array (
                'id' => 27,
                'nombre' => 'JOSE NORBERTO SANCHEZ MARTINEZ S.A.S  CDA CARTAGO',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900339941-7',
                'telefono' => '2126947',
                'direccion' => 'CALLE 4 # 6-32',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:38:59',
                'updated_at' => '2019-06-25 11:38:59',
            ),
            24 => 
            array (
                'id' => 28,
                'nombre' => 'MOTO CASCOS MANIZALEZ',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '8978975',
                'telefono' => '3206779278',
                'direccion' => 'CALLE 15 # 22-51',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:43:19',
                'updated_at' => '2019-06-25 11:43:19',
            ),
            25 => 
            array (
                'id' => 29,
                'nombre' => 'MOTO CASCOS PEREIRA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '43794685-8',
                'telefono' => '3346289',
                'direccion' => 'CARRERA 7 # 12-02',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:46:03',
                'updated_at' => '2019-06-25 11:46:03',
            ),
            26 => 
            array (
                'id' => 30,
                'nombre' => 'AUTOSONIDO CARSTOCK',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '9860401-2',
                'telefono' => '3361313',
                'direccion' => 'CARRERA 11 # 34-01 BUENOS AIRES',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:49:39',
                'updated_at' => '2019-06-25 11:49:39',
            ),
            27 => 
            array (
                'id' => 31,
                'nombre' => 'GRUPO CARDISEL S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900152032-2',
                'telefono' => '',
                'direccion' => 'CARRERA  7 # 43-96 PEREIRA ',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 11:54:43',
                'updated_at' => '2019-06-25 11:54:43',
            ),
            28 => 
            array (
                'id' => 32,
                'nombre' => 'DIVECOL LTDA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900198508-4',
                'telefono' => '',
                'direccion' => 'LA DORADA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 12:07:02',
                'updated_at' => '2019-06-25 12:07:02',
            ),
            29 => 
            array (
                'id' => 33,
                'nombre' => 'PLAZA MOTOS',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '18600545-2',
                'telefono' => '',
                'direccion' => 'PEREIRA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 12:09:46',
                'updated_at' => '2019-06-25 12:09:46',
            ),
            30 => 
            array (
                'id' => 34,
                'nombre' => 'MAURENT EVENTOS',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '9860668-6',
                'telefono' => '3122313244',
                'direccion' => 'SAMARIA 1 ',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 12:13:08',
                'updated_at' => '2019-06-25 12:13:08',
            ),
            31 => 
            array (
                'id' => 35,
                'nombre' => 'ESTACION DE SERVICIO PARQUE OLAYA S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '816003966-3',
                'telefono' => '3240806',
                'direccion' => 'CARRERA 14 # 21-13',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 12:17:32',
                'updated_at' => '2019-06-25 12:17:32',
            ),
            32 => 
            array (
                'id' => 36,
                'nombre' => 'MOTO ASISTENCIA DEL CAFE',
                'estado' => 'Activo',
                'tipo_doc' => 'Cedula Ciudadanía',
                'num_doc' => '24688093-5',
                'telefono' => '3218024516',
                'direccion' => 'CALLE 19 # 12-69 LOCAL 8 FIDUCENTRO',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 12:19:44',
                'updated_at' => '2019-06-25 12:19:44',
            ),
            33 => 
            array (
                'id' => 37,
                'nombre' => 'CDA AJUSTEV MOTOS S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900377240-4',
                'telefono' => '3154458246',
                'direccion' => 'CARRERA 3 # 10-18',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 12:28:06',
                'updated_at' => '2019-06-25 12:28:06',
            ),
            34 => 
            array (
                'id' => 38,
                'nombre' => 'ESCUELA DE AUTOMOVILISMO Y MOTOCICLISMO AUTOSER',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '65782002-6',
                'telefono' => '',
                'direccion' => '',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 12:30:24',
                'updated_at' => '2019-06-25 12:30:24',
            ),
            35 => 
            array (
                'id' => 39,
                'nombre' => 'CENTRO DE DIAGNOSTICO AUTOMOTOR SAN MIGUEL ',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '24622991',
                'telefono' => '3168671883',
                'direccion' => 'CARRERA 7 # 22 -46 AV LIBERTADORES SUPIA ',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-25 12:35:51',
                'updated_at' => '2019-06-25 12:35:51',
            ),
            36 => 
            array (
                'id' => 40,
                'nombre' => 'SOCIEDAD FAMILIAR S.A.S - CDA SAN MIGUEL ',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900391327-4',
                'telefono' => '3113010474',
                'direccion' => 'CRA 7 # 22 - 46  SUPIA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-28 10:20:31',
                'updated_at' => '2019-06-28 10:20:31',
            ),
            37 => 
            array (
                'id' => 42,
                'nombre' => 'CDA SUR DEL TOLIMA S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900877585-5',
                'telefono' => '3203427821',
                'direccion' => 'Calle 10 # 14E - 141 Barrio los Fundadores',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-06-28 10:32:00',
                'updated_at' => '2019-06-28 10:32:00',
            ),
            38 => 
            array (
                'id' => 43,
                'nombre' => 'LA PREVISORA S.A COMPAÑIA DE SEGUROS ',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '860002400-2',
                'telefono' => ' 018000 910554',
                'direccion' => 'Calle 57 No. 9-07 Piso 1.',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-07-03 11:18:47',
                'updated_at' => '2019-07-03 11:18:47',
            ),
            39 => 
            array (
                'id' => 44,
                'nombre' => 'COMPAÑÍA MUNDIAL SEGUROS S.A.',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '860037013-6',
                'telefono' => '327 4712  -  327 4712',
                'direccion' => 'Calle 33 No. 6B-24, Pisos 1, 2 ,3',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-07-03 11:53:37',
                'updated_at' => '2019-07-03 11:53:37',
            ),
            40 => 
            array (
                'id' => 45,
                'nombre' => 'CDA REVISION TECNICOMECANICA Y DE EMISIONES CONTAMINANTES -CARDISEL',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '9001520322',
                'telefono' => '3400800',
                'direccion' => 'DOSQUEBRADAS',
                'user_create_id' => 10,
                'user_update_id' => NULL,
                'created_at' => '2019-07-03 15:49:18',
                'updated_at' => '2019-07-03 15:49:18',
            ),
            41 => 
            array (
                'id' => 46,
                'nombre' => 'INVERSIONES BOCATO S.A.S  CDA UNIMOTOS ',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '9007507554',
                'telefono' => '8642203',
                'direccion' => 'CRA 1D 15-58',
                'user_create_id' => 10,
                'user_update_id' => NULL,
                'created_at' => '2019-07-03 16:25:28',
                'updated_at' => '2019-07-03 16:25:28',
            ),
            42 => 
            array (
                'id' => 47,
                'nombre' => 'INNOVA MOTOS - MARIQUITA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '901273786-1',
                'telefono' => '3222090840',
                'direccion' => 'CALLE 7 # 6-42 ',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-07-10 12:40:12',
                'updated_at' => '2019-07-10 12:40:12',
            ),
            43 => 
            array (
                'id' => 48,
                'nombre' => 'CDA CHECK AND GO S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '901186562-4',
                'telefono' => '3108602905',
                'direccion' => 'CRA 6 # 23-30',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-07-10 12:43:32',
                'updated_at' => '2019-07-10 12:43:32',
            ),
            44 => 
            array (
                'id' => 49,
                'nombre' => 'DIAGNOSTICENTRO LA DORADA LTDA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900200811-1',
                'telefono' => '3207979358',
                'direccion' => 'CRA 2 # 19-69-81  CALLE 20 # 2-01-09',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-08-26 11:10:47',
                'updated_at' => '2019-08-26 11:10:47',
            ),
            45 => 
            array (
                'id' => 50,
                'nombre' => 'FRANCISCO ANTONIO CUELLO ENSUNCHO',
                'estado' => 'Activo',
                'tipo_doc' => 'Cedula Ciudadanía',
                'num_doc' => '1067860006',
                'telefono' => '',
                'direccion' => 'SOLEDAD - BARRANQUIKLLA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-09-20 16:24:27',
                'updated_at' => '2019-09-20 16:24:27',
            ),
            46 => 
            array (
                'id' => 51,
                'nombre' => 'CDA DEL TOLIMA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900149510-0',
                'telefono' => '3185359043',
                'direccion' => 'CALLE 20 # 1-20-40-44 SUR ',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-10-15 15:15:28',
                'updated_at' => '2019-10-15 15:15:28',
            ),
            47 => 
            array (
                'id' => 52,
                'nombre' => 'CARLLANOS VILLAVICENCIO S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900633942-4',
                'telefono' => '3118712473',
                'direccion' => 'CALLE 30 # 24-34 BARRIO PORVENIR',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-11-12 17:08:43',
                'updated_at' => '2019-11-12 17:08:43',
            ),
            48 => 
            array (
                'id' => 53,
                'nombre' => 'SOCIEDAD AUTOGASES DE COLOMBIA S.A.',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '809007992-8',
                'telefono' => '3214120954',
                'direccion' => 'CRA 8 SUR  #60-650 IBAGUE ',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2019-12-03 08:02:53',
                'updated_at' => '2019-12-03 08:02:53',
            ),
            49 => 
            array (
                'id' => 54,
                'nombre' => 'MOTO REPUESTOS - SANTA ROSA',
                'estado' => 'Activo',
                'tipo_doc' => '',
                'num_doc' => '',
                'telefono' => '',
                'direccion' => 'SANTAROSA',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2020-01-08 16:11:13',
                'updated_at' => '2020-01-08 16:11:13',
            ),
            50 => 
            array (
                'id' => 58,
                'nombre' => 'FIP SEGUROS MEDELLIN',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '0',
                'telefono' => '0',
                'direccion' => 'MEDELLIN',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2020-01-09 08:28:30',
                'updated_at' => '2020-01-09 08:28:30',
            ),
            51 => 
            array (
                'id' => 64,
                'nombre' => 'CDA AMBIENTAL CENTER S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900499706',
                'telefono' => '3142549028',
                'direccion' => 'CALLE 26 # 77-79 VILLAVICENCIO',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2020-02-04 19:27:46',
                'updated_at' => '2020-02-04 19:27:46',
            ),
            52 => 
            array (
                'id' => 65,
                'nombre' => 'TECNOCAR ASOCAIADOS S.A.S',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '901021059',
                'telefono' => '',
                'direccion' => 'CRRA 33 # 24-87-8-91-97',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2020-02-04 19:30:15',
                'updated_at' => '2020-02-04 19:30:15',
            ),
            53 => 
            array (
                'id' => 66,
                'nombre' => 'CDA  LA PRADERA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900113525',
                'telefono' => '',
                'direccion' => 'CRA 7A # 55-44',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2020-02-04 19:31:35',
                'updated_at' => '2020-02-04 19:31:35',
            ),
            54 => 
            array (
                'id' => 70,
                'nombre' => 'MONICA VANESSA OSPINA',
                'estado' => 'Activo',
                'tipo_doc' => 'Cedula Ciudadanía',
                'num_doc' => '1054565555',
                'telefono' => '',
                'direccion' => '',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2020-02-04 19:35:05',
                'updated_at' => '2020-02-04 19:35:05',
            ),
            55 => 
            array (
                'id' => 71,
                'nombre' => 'CDA DIAGNOSTICAR IBAGUE',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900',
                'telefono' => '',
                'direccion' => '',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2020-02-04 19:36:07',
                'updated_at' => '2020-02-04 19:36:07',
            ),
            56 => 
            array (
                'id' => 72,
                'nombre' => 'CONTROL MOTOS SECTOR 1- MARIQUITA',
                'estado' => 'Activo',
                'tipo_doc' => 'Nit',
                'num_doc' => '900459746',
                'telefono' => '2525303',
                'direccion' => 'CRA 9 # 10-78 EL CARMEN ',
                'user_create_id' => 101,
                'user_update_id' => NULL,
                'created_at' => '2020-02-04 19:37:30',
                'updated_at' => '2020-02-04 19:37:30',
            ),
        ));
        
        
    }
}
