<?php

use Illuminate\Database\Seeder;

class PuntosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('puntos')->delete();
        
        \DB::table('puntos')->insert(array (
            0 => 
            array (
                'id' => 1,
                'zona_id' => NULL,
                'nombre' => 'PEREIRA - ASISTIMOTOS ',
                'prefijo' => 'PER',
                'increment' => 5358,
                'estado' => 'Activo',
                'direccion' => 'CL. 18 #11-56, PEREIRA, RISARALDA',
                'telefono' => '3172520 Ext: 2',
                'descripcion' => 'PRINCIPAL',
                'municipio_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-03-12 17:38:27',
            ),
            1 => 
            array (
                'id' => 2,
                'zona_id' => NULL,
                'nombre' => 'CARTAGO - CDA CARTAGO',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'CALLE 4 # 6 - 32',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 277,
                'created_at' => '2017-09-05 11:41:53',
                'updated_at' => '2019-05-29 11:36:08',
            ),
            2 => 
            array (
                'id' => 3,
                'zona_id' => NULL,
                'nombre' => 'CHINCHINA',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'CALLE 15 # 5A-13',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 304,
                'created_at' => '2017-09-05 11:42:47',
                'updated_at' => '2019-05-29 11:36:59',
            ),
            3 => 
            array (
                'id' => 4,
                'zona_id' => NULL,
                'nombre' => 'MANIZALEZ - CELULAR EXPRESS',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'CRA 23 # 23 -60 EDIFICIO CUELLAR OFICINA 408A',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 3,
                'created_at' => '2017-09-05 11:43:38',
                'updated_at' => '2019-05-29 11:37:59',
            ),
            4 => 
            array (
                'id' => 5,
                'zona_id' => NULL,
                'nombre' => 'SUPIA - CDA SAN MIGUEL',
                'prefijo' => 'SUP',
                'increment' => 5668,
                'estado' => 'Activo',
                'direccion' => 'SUPIA',
                'telefono' => '3217721813',
                'descripcion' => 'CDA SAN MIGUEL Y SUPIA',
                'municipio_id' => 1069,
                'created_at' => '2017-09-05 15:03:58',
                'updated_at' => '2020-02-05 09:32:03',
            ),
            5 => 
            array (
                'id' => 6,
                'zona_id' => NULL,
                'nombre' => 'PEREIRA - EMPREDENET',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'CRA 6 CALLE 18',
                'telefono' => NULL,
                'descripcion' => 'COMISIóN DE CELULARES',
                'municipio_id' => 1,
                'created_at' => '2017-09-27 15:43:31',
                'updated_at' => '2019-05-29 11:39:02',
            ),
            6 => 
            array (
                'id' => 7,
                'zona_id' => NULL,
                'nombre' => 'URRAO ANTIOQUIA - CAD CACIQUE TONEE',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CRA 31 #20-405',
                'telefono' => NULL,
                'descripcion' => 'ANTIOQUIA',
                'municipio_id' => 1151,
                'created_at' => '2017-09-27 15:51:41',
                'updated_at' => '2019-05-29 11:40:14',
            ),
            7 => 
            array (
                'id' => 8,
                'zona_id' => NULL,
                'nombre' => 'IBAGUE - ASISTIMOTOS ',
                'prefijo' => 'IBA',
                'increment' => 2752,
                'estado' => 'Activo',
                'direccion' => 'CRA-5A CALLE-21, LOCAL 8',
                'telefono' => '3136509524',
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2017-09-27 15:54:15',
                'updated_at' => '2020-02-08 13:49:04',
            ),
            8 => 
            array (
                'id' => 9,
                'zona_id' => 0,
                'nombre' => 'DOSQUEBRADAS - CDA EJE CAFETERO',
                'prefijo' => 'DOS',
                'increment' => 706,
                'estado' => 'Inactivo',
                'direccion' => 'CRA 2 NORTE # 1-122, VIA EL POLLO',
                'telefono' => '3104962439',
                'descripcion' => '',
                'municipio_id' => 2,
                'created_at' => '2017-11-23 10:16:18',
                'updated_at' => '2019-10-11 09:14:00',
            ),
            9 => 
            array (
                'id' => 10,
                'zona_id' => 0,
                'nombre' => 'LA DORADA - CDA DIVECOL',
                'prefijo' => 'DOR',
                'increment' => 2221,
                'estado' => 'Inactivo',
                'direccion' => 'CRA 2 #18-43 CDA DIVECOL',
                'telefono' => '3214565304',
                'descripcion' => 'PUNTO CDA',
                'municipio_id' => 568,
                'created_at' => '2017-12-12 07:53:35',
                'updated_at' => '2019-10-21 06:15:18',
            ),
            10 => 
            array (
                'id' => 11,
                'zona_id' => NULL,
                'nombre' => 'NEIVA - CDA UNIMOTOS',
                'prefijo' => 'EVA',
                'increment' => 3310,
                'estado' => 'Activo',
                'direccion' => 'CDA UNIMOTOS',
                'telefono' => '3176455433',
                'descripcion' => 'CDA NEIVA',
                'municipio_id' => 710,
                'created_at' => '2017-12-12 07:58:02',
                'updated_at' => '2020-02-08 13:39:23',
            ),
            11 => 
            array (
                'id' => 12,
                'zona_id' => NULL,
                'nombre' => 'PACORA - LA BODEGA DE LOS CELULARES',
                'prefijo' => 'PAC',
                'increment' => 0,
                'estado' => 'Inactivo',
                'direccion' => 'LA BODEGA DE LOS CELULARES',
                'telefono' => NULL,
                'descripcion' => 'LA BODEGA DE LOS CELULARES',
                'municipio_id' => 741,
                'created_at' => '2017-12-12 08:01:24',
                'updated_at' => '2019-05-29 11:16:35',
            ),
            12 => 
            array (
                'id' => 13,
                'zona_id' => NULL,
                'nombre' => 'BUGA - CDA BUENA ATMOSFERA',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'BUGA',
                'telefono' => NULL,
                'descripcion' => 'CDA DE BUGA',
                'municipio_id' => 497,
                'created_at' => '2017-12-12 08:03:51',
                'updated_at' => '2019-05-29 11:14:33',
            ),
            13 => 
            array (
                'id' => 14,
                'zona_id' => NULL,
                'nombre' => 'CALDAS ANTIOQUIA',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'CRA 50 139-32',
                'telefono' => NULL,
                'descripcion' => 'TRAMITES',
                'municipio_id' => 248,
                'created_at' => '2018-01-26 11:46:27',
                'updated_at' => '2019-05-29 11:15:27',
            ),
            14 => 
            array (
                'id' => 15,
                'zona_id' => 0,
                'nombre' => 'PEREIRA - CARSEGUROS',
                'prefijo' => '',
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'PEREIRA',
                'telefono' => '',
                'descripcion' => 'ALIADO',
                'municipio_id' => 877,
                'created_at' => '2018-02-18 15:26:36',
                'updated_at' => '2019-10-21 06:17:01',
            ),
            15 => 
            array (
                'id' => 16,
                'zona_id' => NULL,
                'nombre' => 'SANTA ROSA DE CABAL - MOTO REPUESTOS',
                'prefijo' => NULL,
                'increment' => 25,
                'estado' => 'Activo',
                'direccion' => 'SANTA ROSA',
                'telefono' => NULL,
                'descripcion' => 'ALIADO',
                'municipio_id' => 877,
                'created_at' => '2018-02-18 15:27:07',
                'updated_at' => '2020-01-22 09:56:16',
            ),
            16 => 
            array (
                'id' => 17,
                'zona_id' => NULL,
                'nombre' => 'MANIZALES - MOTO CASCOS ',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'MANIZALES',
                'telefono' => NULL,
                'descripcion' => 'ALIADO',
                'municipio_id' => 877,
                'created_at' => '2018-02-18 15:28:23',
                'updated_at' => '2019-05-29 11:11:29',
            ),
            17 => 
            array (
                'id' => 18,
                'zona_id' => NULL,
                'nombre' => 'PEREIRA - MOTO CASCOS ',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'PEREIRA',
                'telefono' => NULL,
                'descripcion' => 'ALIADO',
                'municipio_id' => 877,
                'created_at' => '2018-02-18 15:28:45',
                'updated_at' => '2019-05-29 11:10:36',
            ),
            18 => 
            array (
                'id' => 19,
                'zona_id' => NULL,
                'nombre' => 'PEREIRA - GRUPO CARDISEL SAS',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'DOSQUEBRADAS',
                'telefono' => NULL,
                'descripcion' => 'ALIADO',
                'municipio_id' => 877,
                'created_at' => '2018-02-18 15:31:03',
                'updated_at' => '2019-05-29 11:09:18',
            ),
            19 => 
            array (
                'id' => 20,
                'zona_id' => NULL,
                'nombre' => 'CALI - CDA DIAGNOSTICAR',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'CALLE 23 NO. 18-80',
                'telefono' => NULL,
                'descripcion' => 'ALIADO',
                'municipio_id' => 251,
                'created_at' => '2018-03-16 12:24:46',
                'updated_at' => '2019-05-29 11:07:58',
            ),
            20 => 
            array (
                'id' => 21,
                'zona_id' => NULL,
                'nombre' => 'PEREIRA PRINCIPAL',
                'prefijo' => 'PRI',
                'increment' => 4,
                'estado' => 'Inactivo',
                'direccion' => 'CRA 6 17-62 FEGOVER 203',
                'telefono' => NULL,
                'descripcion' => 'OFICINA PRINCIPAL',
                'municipio_id' => 1,
                'created_at' => '2018-03-16 15:57:45',
                'updated_at' => '2019-05-29 11:05:53',
            ),
            21 => 
            array (
                'id' => 22,
                'zona_id' => NULL,
                'nombre' => 'CARTAGO - MR ASESORES ',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'CALLE 16C #8-33',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 277,
                'created_at' => '2018-04-12 17:43:59',
                'updated_at' => '2019-05-29 11:07:16',
            ),
            22 => 
            array (
                'id' => 23,
                'zona_id' => NULL,
                'nombre' => 'BUGA - CDA TEAM ADVANCE',
                'prefijo' => 'BUG',
                'increment' => 5134,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 10 #7-66',
                'telefono' => '2382911 - 3122435113',
                'descripcion' => '',
                'municipio_id' => 497,
                'created_at' => '2018-05-16 16:51:10',
                'updated_at' => '2020-02-05 08:47:44',
            ),
            23 => 
            array (
                'id' => 24,
                'zona_id' => NULL,
                'nombre' => 'LA UNION VALLE -  CDA MOTO LA UNION',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CALLE 14 #10-69',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 596,
                'created_at' => '2018-05-16 17:05:45',
                'updated_at' => '2019-05-29 11:03:45',
            ),
            24 => 
            array (
                'id' => 25,
                'zona_id' => NULL,
                'nombre' => 'PEREIRA - ESTACION PARQUE OLAYA',
                'prefijo' => 'OLA',
                'increment' => 18,
                'estado' => 'Activo',
                'direccion' => 'AV. 30 DE AGOSTO #21-27',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 1,
                'created_at' => '2018-05-16 17:18:16',
                'updated_at' => '2019-12-19 16:47:31',
            ),
            25 => 
            array (
                'id' => 26,
                'zona_id' => NULL,
                'nombre' => 'TULUA - CDA LA PISTA ',
                'prefijo' => 'PIS',
                'increment' => 2242,
                'estado' => 'Activo',
                'direccion' => 'CALLE 13 # 38A-164 VIA ESTAMBUL',
                'telefono' => '3222120115',
                'descripcion' => '',
                'municipio_id' => 1131,
                'created_at' => '2018-07-27 16:09:18',
                'updated_at' => '2020-02-08 12:04:01',
            ),
            26 => 
            array (
                'id' => 27,
                'zona_id' => 0,
                'nombre' => 'SOACHA - CDA CEDIPLUS',
                'prefijo' => 'SOA',
                'increment' => 1114,
                'estado' => 'Inactivo',
                'direccion' => 'CRA 4 NO 20-84 SOACHA CUNDINAMARCA',
                'telefono' => '3122800030',
                'descripcion' => '',
                'municipio_id' => 1040,
                'created_at' => '2018-07-27 16:14:27',
                'updated_at' => '2019-11-28 16:25:34',
            ),
            27 => 
            array (
                'id' => 28,
                'zona_id' => NULL,
                'nombre' => 'PEREIRA -  CAF',
                'prefijo' => 'CAF',
                'increment' => 6042,
                'estado' => 'Activo',
                'direccion' => 'CRA 6 17-62 ',
                'telefono' => '3340898',
                'descripcion' => '',
                'municipio_id' => 1,
                'created_at' => '2018-09-13 11:59:30',
                'updated_at' => '2020-02-08 12:01:55',
            ),
            28 => 
            array (
                'id' => 29,
                'zona_id' => NULL,
                'nombre' => 'BUGA - PUNTO SOAT ',
                'prefijo' => 'DUK',
                'increment' => 3174,
                'estado' => 'Activo',
                'direccion' => 'PUNTO SOAT CRA 8 6 ESQUINA',
                'telefono' => '3188835844',
                'descripcion' => '',
                'municipio_id' => 497,
                'created_at' => '2018-12-06 10:39:45',
                'updated_at' => '2020-02-08 12:59:39',
            ),
            29 => 
            array (
                'id' => 30,
                'zona_id' => NULL,
                'nombre' => 'IBAGUE - CDA TECNIMOTORS ',
                'prefijo' => 'IBS',
                'increment' => 3339,
                'estado' => 'Activo',
                'direccion' => 'SALADO',
                'telefono' => '2596125',
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2018-12-06 10:44:48',
                'updated_at' => '2020-02-08 12:13:31',
            ),
            30 => 
            array (
                'id' => 31,
                'zona_id' => 0,
                'nombre' => 'SOLEDAD ATLANTICO - CDA LOS PRIMOS',
                'prefijo' => 'SOL',
                'increment' => 79,
                'estado' => 'Inactivo',
                'direccion' => 'CALLE 18 N 28A - 04',
                'telefono' => '3017801986',
                'descripcion' => '',
                'municipio_id' => 1047,
                'created_at' => '2019-01-24 10:23:37',
                'updated_at' => '2019-10-11 09:12:49',
            ),
            31 => 
            array (
                'id' => 32,
                'zona_id' => NULL,
                'nombre' => 'NEIVA - CAMACHOS ASESORES',
                'prefijo' => NULL,
                'increment' => 118,
                'estado' => 'Activo',
                'direccion' => 'CC COMUNEROS OFICINA 3043',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 710,
                'created_at' => '2019-01-24 10:30:16',
                'updated_at' => '2019-11-26 18:06:52',
            ),
            32 => 
            array (
                'id' => 33,
                'zona_id' => NULL,
                'nombre' => 'CDA MOTOS DE LA SEXTA',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'IBAGUE',
                'telefono' => NULL,
                'descripcion' => 'PUTNO ACTUALMENTE CERRADO',
                'municipio_id' => 533,
                'created_at' => '2019-02-03 18:26:41',
                'updated_at' => '2019-05-29 10:56:27',
            ),
            33 => 
            array (
                'id' => 34,
                'zona_id' => NULL,
                'nombre' => 'PEREIRA - MULTINTEGRAL SAS',
                'prefijo' => 'MUL',
                'increment' => 21,
                'estado' => 'Activo',
                'direccion' => 'CRA 14 18-09 ',
                'telefono' => '3128213554',
                'descripcion' => '',
                'municipio_id' => 1,
                'created_at' => '2019-02-05 15:15:27',
                'updated_at' => '2019-08-16 16:20:04',
            ),
            34 => 
            array (
                'id' => 35,
                'zona_id' => 0,
                'nombre' => 'DOSQUEBRADAS - CDA CARDISEL',
                'prefijo' => 'CAR',
                'increment' => 230,
                'estado' => 'Activo',
                'direccion' => 'LA ROSA Y LA ROMELIA',
                'telefono' => '',
                'descripcion' => '',
                'municipio_id' => 2,
                'created_at' => '2019-02-14 18:12:22',
                'updated_at' => '2020-02-08 14:25:23',
            ),
            35 => 
            array (
                'id' => 36,
                'zona_id' => NULL,
                'nombre' => 'IBAGUE - PUNTO GORA ASISTIMOTOS',
                'prefijo' => 'PGA',
                'increment' => 372,
                'estado' => 'Activo',
                'direccion' => 'IBAGUE',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2019-02-26 09:08:21',
                'updated_at' => '2019-10-21 17:42:55',
            ),
            36 => 
            array (
                'id' => 37,
                'zona_id' => NULL,
                'nombre' => 'IBAGUE - CONTROL MOTOS ',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CRA 5 63-15',
                'telefono' => NULL,
                'descripcion' => 'CDA',
                'municipio_id' => 533,
                'created_at' => '2019-03-12 15:52:32',
                'updated_at' => '2019-05-29 10:54:03',
            ),
            37 => 
            array (
                'id' => 38,
                'zona_id' => 0,
                'nombre' => 'PUERTO BOYACA - CDA DIVECOL',
                'prefijo' => 'DIV',
                'increment' => 78,
                'estado' => 'Inactivo',
                'direccion' => 'PUERTO BOYACA',
                'telefono' => '',
                'descripcion' => 'CDA',
                'municipio_id' => 568,
                'created_at' => '2019-03-12 15:53:12',
                'updated_at' => '2019-10-21 06:16:09',
            ),
            38 => 
            array (
                'id' => 39,
                'zona_id' => 0,
                'nombre' => 'BOGOTA -  CDA MAXI MOTO',
                'prefijo' => 'MAX',
                'increment' => 167,
                'estado' => 'Activo',
                'direccion' => 'AV 1 DE MAYO 68F-25',
                'telefono' => '3122800030',
                'descripcion' => 'CDA',
                'municipio_id' => 209,
                'created_at' => '2019-03-12 15:54:08',
                'updated_at' => '2020-02-08 10:06:53',
            ),
            39 => 
            array (
                'id' => 40,
                'zona_id' => NULL,
                'nombre' => 'LA DORADA - FIP SEGUROS',
                'prefijo' => 'FIP',
                'increment' => 2230,
                'estado' => 'Activo',
                'direccion' => 'CRA 2 17-23 ',
                'telefono' => '3222090840',
                'descripcion' => '',
                'municipio_id' => 568,
                'created_at' => '2019-05-06 16:43:07',
                'updated_at' => '2020-02-08 11:16:32',
            ),
            40 => 
            array (
                'id' => 41,
                'zona_id' => NULL,
                'nombre' => 'DOSQUEBRADAS - CERTIFIMOTOS',
                'prefijo' => NULL,
                'increment' => 590,
                'estado' => 'Activo',
                'direccion' => 'PLAZUELA DE POSTOBON',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 2,
                'created_at' => '2019-05-14 15:51:36',
                'updated_at' => '2019-10-18 15:26:08',
            ),
            41 => 
            array (
                'id' => 42,
                'zona_id' => 0,
                'nombre' => 'CHAPARRAL TOLIMA - CDA DEL SUR DEL TOLIMA',
                'prefijo' => 'CHP',
                'increment' => 520,
                'estado' => 'Activo',
                'direccion' => 'CALLE 10 # 14E-141',
                'telefono' => '3143894889',
                'descripcion' => '',
                'municipio_id' => 293,
                'created_at' => '2019-05-14 15:52:59',
                'updated_at' => '2020-02-08 13:29:55',
            ),
            42 => 
            array (
                'id' => 43,
                'zona_id' => NULL,
                'nombre' => 'SAN GIL BUCARAMANGA - CDA MOTOS EL GALLINERAL',
                'prefijo' => NULL,
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 12 N. 18-43 UND 103',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 937,
                'created_at' => '2019-05-14 15:57:19',
                'updated_at' => '2019-05-29 10:45:31',
            ),
            43 => 
            array (
                'id' => 44,
                'zona_id' => 0,
                'nombre' => 'MARIQUITA INNOVA MOTOS',
                'prefijo' => 'MRQ',
                'increment' => 19,
                'estado' => 'Inactivo',
                'direccion' => 'CALLE 7 #6-49',
                'telefono' => '',
                'descripcion' => 'VENTA DE MOTOS Y EXPEDICIóN DE SOAT',
                'municipio_id' => 653,
                'created_at' => '2019-06-12 09:49:08',
                'updated_at' => '2019-12-24 11:57:36',
            ),
            44 => 
            array (
                'id' => 45,
                'zona_id' => NULL,
                'nombre' => 'MARIQUITA INNOVAMOTOS',
                'prefijo' => 'MQT',
                'increment' => 285,
                'estado' => 'Activo',
                'direccion' => 'CALLE 7 # 6-42',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 653,
                'created_at' => '2019-06-17 15:15:29',
                'updated_at' => '2020-02-08 11:27:00',
            ),
            45 => 
            array (
                'id' => 47,
                'zona_id' => 0,
                'nombre' => 'IBAGUÉ CDA CHECK AND GO',
                'prefijo' => 'CHE',
                'increment' => 719,
                'estado' => 'Activo',
                'direccion' => 'CRA 6  # 23-30 BARRIO EL CARMEN',
                'telefono' => '3146782094 - 2809639',
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2019-07-05 08:15:29',
                'updated_at' => '2020-02-08 12:56:39',
            ),
            46 => 
            array (
                'id' => 48,
                'zona_id' => 0,
                'nombre' => 'LA DORADA FACILCREDITOS SAS',
                'prefijo' => 'FAC',
                'increment' => 1157,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 3 NO 11-25C',
                'telefono' => '3155682194',
                'descripcion' => 'PUNTO DE FACILCREDITOS SAS, MANEJO DE NEGOCIOS DE CRéDITO DE ELECTRODOMéSTICOS.. ',
                'municipio_id' => 568,
                'created_at' => '2019-07-22 17:06:07',
                'updated_at' => '2020-02-08 13:45:42',
            ),
            47 => 
            array (
                'id' => 49,
                'zona_id' => 0,
                'nombre' => 'LA DORADA - DIAGNOSTICENTRO',
                'prefijo' => 'DIA',
                'increment' => 1170,
                'estado' => 'Activo',
                'direccion' => 'CR 2 19 69 81 CALLE 20 2 01 09',
                'telefono' => NULL,
                'descripcion' => '',
                'municipio_id' => 568,
                'created_at' => '2019-07-26 10:10:42',
                'updated_at' => '2020-02-08 12:23:20',
            ),
            48 => 
            array (
                'id' => 50,
                'zona_id' => 0,
                'nombre' => 'MEDELLIN FIP SEGUROS',
                'prefijo' => 'MLL',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CALLE 33 # 65-86',
                'telefono' => '3164413574',
                'descripcion' => '',
                'municipio_id' => 659,
                'created_at' => '2019-08-24 08:59:06',
                'updated_at' => '2019-08-24 09:00:09',
            ),
            49 => 
            array (
                'id' => 51,
                'zona_id' => 0,
                'nombre' => 'QUIMBAYA CDA TECNIMOTORS QUIMBAYA',
                'prefijo' => 'QBY',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CALLE 19 # 7-21',
                'telefono' => '3213517855',
                'descripcion' => '',
                'municipio_id' => 849,
                'created_at' => '2019-09-02 14:44:45',
                'updated_at' => '2019-09-02 14:45:22',
            ),
            50 => 
            array (
                'id' => 52,
                'zona_id' => 0,
                'nombre' => 'IBAGUÉ CDA DEL TOLIMA',
                'prefijo' => 'IBA',
                'increment' => 377,
                'estado' => 'Activo',
                'direccion' => 'CALLE 20 1-20',
                'telefono' => '3175170117',
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2019-09-02 16:12:29',
                'updated_at' => '2020-02-08 13:11:53',
            ),
            51 => 
            array (
                'id' => 53,
                'zona_id' => 0,
                'nombre' => 'IBAGUE - CDA AUTO-GASES',
                'prefijo' => 'IBA',
                'increment' => 16,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 8 SUR AVENIDA MIRO LINDO NO 60-650',
                'telefono' => '3214120954',
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2019-09-03 15:48:02',
                'updated_at' => '2020-02-08 09:07:58',
            ),
            52 => 
            array (
                'id' => 54,
                'zona_id' => 0,
                'nombre' => 'IBAGUÉ CDA AUTOGASES',
                'prefijo' => 'IBA',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CRA 8 SUR 60-650 VIA MIROLINDO',
                'telefono' => '3214120954',
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2019-09-03 16:17:21',
                'updated_at' => '2019-09-03 16:17:21',
            ),
            53 => 
            array (
                'id' => 55,
                'zona_id' => 0,
                'nombre' => 'VILLAVICENCIO - CDA CARLLANOS',
                'prefijo' => 'VCC',
                'increment' => 57,
                'estado' => 'Activo',
                'direccion' => 'CALLE 30 # 24- 34',
                'telefono' => '3212478813-6679951',
                'descripcion' => '',
                'municipio_id' => 1190,
                'created_at' => '2019-09-25 09:32:15',
                'updated_at' => '2020-02-07 18:37:48',
            ),
            54 => 
            array (
                'id' => 56,
                'zona_id' => 0,
                'nombre' => 'VILLAVICENCIO CDA TECNO CAR',
                'prefijo' => 'VIL',
                'increment' => 6,
                'estado' => 'Activo',
                'direccion' => 'CRA 33 # 24-97 SAN BENITO',
                'telefono' => '6833969-3225301337',
                'descripcion' => '',
                'municipio_id' => 1190,
                'created_at' => '2019-09-25 09:35:54',
                'updated_at' => '2019-12-03 07:59:08',
            ),
            55 => 
            array (
                'id' => 57,
                'zona_id' => 0,
                'nombre' => 'ACACÌAS CDA SCOOTERS',
                'prefijo' => 'ACA',
                'increment' => NULL,
                'estado' => 'Inactivo',
                'direccion' => 'CRA 21 # 15-24 B COOPERATIVO',
                'telefono' => '3118006270-6574622',
                'descripcion' => '',
                'municipio_id' => 104,
                'created_at' => '2019-09-25 09:37:32',
                'updated_at' => '2020-02-03 10:01:48',
            ),
            56 => 
            array (
                'id' => 58,
                'zona_id' => 0,
                'nombre' => 'IBAGUÉ CDA DIAGNOSTICAR',
                'prefijo' => 'IBA',
                'increment' => 14,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 20 SUR # 107-102',
                'telefono' => '2690034',
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2019-10-15 14:24:50',
                'updated_at' => '2020-02-08 11:55:10',
            ),
            57 => 
            array (
                'id' => 59,
                'zona_id' => 0,
                'nombre' => 'PEREIRA CARDISEL TURIN',
                'prefijo' => 'PER',
                'increment' => 141,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 7 # 43-96',
                'telefono' => '3114197313',
                'descripcion' => '',
                'municipio_id' => 1,
                'created_at' => '2019-10-18 14:10:26',
                'updated_at' => '2020-02-08 13:50:42',
            ),
            58 => 
            array (
                'id' => 60,
                'zona_id' => 0,
                'nombre' => 'MULTINTEGRAL LA 18',
                'prefijo' => 'MUL',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CR 14 # 18 - 09',
                'telefono' => '3335969',
                'descripcion' => '',
                'municipio_id' => 1,
                'created_at' => '2019-10-24 15:15:11',
                'updated_at' => '2019-10-24 15:37:17',
            ),
            59 => 
            array (
                'id' => 61,
                'zona_id' => 0,
                'nombre' => 'VILLAVICENCIO - CDA AMBIENTAL CENTER',
                'prefijo' => 'VIC',
                'increment' => 17,
                'estado' => 'Activo',
                'direccion' => 'CALLE 26 #34-77',
                'telefono' => '3124891124',
                'descripcion' => '',
                'municipio_id' => 1190,
                'created_at' => '2019-12-05 17:00:29',
                'updated_at' => '2020-02-08 13:50:03',
            ),
            60 => 
            array (
                'id' => 62,
                'zona_id' => 0,
                'nombre' => 'NEIVA - CDA LA PRADERA',
                'prefijo' => 'PRA',
                'increment' => 74,
                'estado' => 'Activo',
                'direccion' => 'LA PRADERA ',
                'telefono' => '3202971905',
                'descripcion' => 'FALTA DIRECCION ',
                'municipio_id' => 2,
                'created_at' => '2019-12-06 15:29:40',
                'updated_at' => '2020-02-05 17:42:39',
            ),
            61 => 
            array (
                'id' => 63,
                'zona_id' => 0,
                'nombre' => 'PALMIRA - CDA PARAISO',
                'prefijo' => 'PAL',
                'increment' => 2,
                'estado' => 'Activo',
                'direccion' => 'BARRIO PARAISO EN PALMIRA VALLE',
                'telefono' => '3122549281',
                'descripcion' => '',
                'municipio_id' => 756,
                'created_at' => '2020-01-10 09:07:38',
                'updated_at' => '2020-02-07 15:49:19',
            ),
            62 => 
            array (
                'id' => 64,
                'zona_id' => 0,
                'nombre' => 'FUSAGASUGA - CDA CONTROL AUTOS',
                'prefijo' => 'FUS',
                'increment' => 14,
                'estado' => 'Activo',
                'direccion' => 'POR LA TERMINAL, POR EL CUERPO DE BOMBEROS',
                'telefono' => '3122549281',
                'descripcion' => '',
                'municipio_id' => 462,
                'created_at' => '2020-01-10 09:09:02',
                'updated_at' => '2020-02-07 17:39:27',
            ),
            63 => 
            array (
                'id' => 65,
                'zona_id' => 0,
                'nombre' => 'PEREIRA - CDA AUTOMAS PEREIRA',
                'prefijo' => 'PRA',
                'increment' => 27,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 10 CALLE 38',
                'telefono' => '3122549281',
                'descripcion' => '',
                'municipio_id' => 1,
                'created_at' => '2020-01-10 09:16:22',
                'updated_at' => '2020-02-08 09:49:41',
            ),
            64 => 
            array (
                'id' => 66,
                'zona_id' => 0,
                'nombre' => 'MANZANRES - CDA DE LA MONTAÑA',
                'prefijo' => 'MON',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CALLE 9 # 5 - 103',
                'telefono' => 'Por actualizar',
                'descripcion' => '',
                'municipio_id' => 646,
                'created_at' => '2020-01-17 17:38:55',
                'updated_at' => '2020-01-17 17:38:55',
            ),
            65 => 
            array (
                'id' => 67,
                'zona_id' => 0,
                'nombre' => 'BOGOTA - MOTO FULL',
                'prefijo' => 'MTF',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'TRANSVERSAL 73D # 38C - 56 SUR',
                'telefono' => 'Pendiente',
                'descripcion' => '',
                'municipio_id' => 209,
                'created_at' => '2020-01-17 17:50:07',
                'updated_at' => '2020-01-17 17:50:07',
            ),
            66 => 
            array (
                'id' => 68,
                'zona_id' => 0,
                'nombre' => 'PALMIRA- CDA LAS PALMAS ',
                'prefijo' => 'PAL',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CRA. 34B ##42-16, PALMIRA, VALLE DEL CAUCA',
                'telefono' => '3122549281',
                'descripcion' => '',
                'municipio_id' => 756,
                'created_at' => '2020-01-24 12:55:30',
                'updated_at' => '2020-01-24 12:55:30',
            ),
            67 => 
            array (
                'id' => 69,
                'zona_id' => 0,
                'nombre' => 'BOGOTÀ - CDA AUTOMAS CALLE 13 PERITAR',
                'prefijo' => 'DCB',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'DIAGONAL 13 NO 69-18',
                'telefono' => '322-2081400',
                'descripcion' => '',
                'municipio_id' => 209,
                'created_at' => '2020-01-24 17:44:24',
                'updated_at' => '2020-01-24 17:44:24',
            ),
            68 => 
            array (
                'id' => 70,
                'zona_id' => 0,
                'nombre' => 'GIRARDOT - CDA CONTROL AUTOS LAS ACACIASGIRARDOT',
                'prefijo' => 'GIR',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 10 NO 38-05',
                'telefono' => '322-2081400',
                'descripcion' => '',
                'municipio_id' => 480,
                'created_at' => '2020-01-24 17:46:30',
                'updated_at' => '2020-01-24 17:46:30',
            ),
            69 => 
            array (
                'id' => 71,
                'zona_id' => 0,
                'nombre' => 'FLORENCIA - CDA MOTOMAS LTDA',
                'prefijo' => 'FLO',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 11 NO 10-66',
                'telefono' => '322-2081400',
                'descripcion' => '',
                'municipio_id' => 443,
                'created_at' => '2020-01-24 17:48:24',
                'updated_at' => '2020-01-24 17:48:24',
            ),
            70 => 
            array (
                'id' => 72,
                'zona_id' => 0,
                'nombre' => 'BOGOTA - CDA AUTOMAS LTDA CARRERA 46 NO 134-55',
                'prefijo' => 'DCA',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 46 NO 134-55 NORTE',
                'telefono' => '322-2081400',
                'descripcion' => '',
                'municipio_id' => 209,
                'created_at' => '2020-01-24 17:53:59',
                'updated_at' => '2020-01-24 17:53:59',
            ),
            71 => 
            array (
                'id' => 73,
                'zona_id' => 0,
                'nombre' => 'BOGOTA - CDA AUTOMAS LTDA 1 DE MAYO',
                'prefijo' => 'DCC',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'AVENIDA PRIMERO DE MAYO NO 29-33',
                'telefono' => '322-2081400',
                'descripcion' => '',
                'municipio_id' => 209,
                'created_at' => '2020-01-24 17:56:00',
                'updated_at' => '2020-01-24 17:56:00',
            ),
            72 => 
            array (
                'id' => 74,
                'zona_id' => 0,
                'nombre' => 'MEDELLIN - CDA AUTOMAS LAURELES',
                'prefijo' => 'MEL',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CALLE 33  NO 78-158',
                'telefono' => '322-2081400',
                'descripcion' => '',
                'municipio_id' => 659,
                'created_at' => '2020-01-24 17:57:45',
                'updated_at' => '2020-01-24 17:57:45',
            ),
            73 => 
            array (
                'id' => 75,
                'zona_id' => 0,
                'nombre' => 'CALI - CDA AUTOMAS CALI AV CAÑAS GORDAS',
                'prefijo' => 'CAL',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CALLE 18 NO 113-55',
                'telefono' => '322-2081400',
                'descripcion' => '',
                'municipio_id' => 251,
                'created_at' => '2020-01-24 18:00:26',
                'updated_at' => '2020-01-24 18:00:26',
            ),
            74 => 
            array (
                'id' => 76,
                'zona_id' => 0,
                'nombre' => 'MEDELLIN - CDA GRUPO AUTOPOR',
                'prefijo' => 'MDI',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CALLE 10 NO 56-44',
                'telefono' => '322-2081400',
                'descripcion' => '',
                'municipio_id' => 659,
                'created_at' => '2020-01-24 18:02:59',
                'updated_at' => '2020-01-24 18:02:59',
            ),
            75 => 
            array (
                'id' => 77,
                'zona_id' => 0,
                'nombre' => 'MARIQUITA - CONTROL MOTOS',
                'prefijo' => 'MIT',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 9 NO 10-74 MARIQUITA TOLIMA',
                'telefono' => '3102784779',
                'descripcion' => 'SOLUCIONES EMPRESARIALES DE COMERCIO SAS',
                'municipio_id' => 653,
                'created_at' => '2020-01-28 15:50:43',
                'updated_at' => '2020-01-28 15:50:43',
            ),
            76 => 
            array (
                'id' => 78,
                'zona_id' => 0,
                'nombre' => 'NEIVA - CDA SAN PEDRO',
                'prefijo' => 'NVA',
                'increment' => 20,
                'estado' => 'Activo',
                'direccion' => 'CENTRO',
                'telefono' => '3122549281',
                'descripcion' => '',
                'municipio_id' => 710,
                'created_at' => '2020-01-29 15:52:40',
                'updated_at' => '2020-02-08 13:50:36',
            ),
            77 => 
            array (
                'id' => 79,
                'zona_id' => 0,
                'nombre' => 'IBAGUE - CDA LA REVISION',
                'prefijo' => 'LRV',
                'increment' => 6,
                'estado' => 'Activo',
                'direccion' => 'AVENIDA 5',
                'telefono' => '3122549281',
                'descripcion' => '',
                'municipio_id' => 533,
                'created_at' => '2020-01-29 16:02:54',
                'updated_at' => '2020-02-08 13:55:32',
            ),
            78 => 
            array (
                'id' => 80,
                'zona_id' => 0,
                'nombre' => 'PALMIRA - CDA LAS PALMAS',
                'prefijo' => 'PLA',
                'increment' => NULL,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 34 NO 42-16 BARRIO INDUSTRIAL EN PALMIRA',
                'telefono' => '3122549281',
                'descripcion' => '',
                'municipio_id' => 756,
                'created_at' => '2020-02-03 10:05:57',
                'updated_at' => '2020-02-03 10:05:57',
            ),
            79 => 
            array (
                'id' => 81,
                'zona_id' => 0,
                'nombre' => 'ESPINAL - CDA DIANOSTI MOTOS ESPINAL',
                'prefijo' => 'ESP',
                'increment' => 2,
                'estado' => 'Activo',
                'direccion' => 'CARRERA 4 NO 14-52 RONDON',
                'telefono' => '3122549281',
                'descripcion' => '',
                'municipio_id' => 436,
                'created_at' => '2020-02-05 08:48:30',
                'updated_at' => '2020-02-07 17:30:21',
            ),
        ));
        
        
    }
}
