<?php

use Illuminate\Database\Seeder;

class RefProductosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        \DB::table('ref_productos')->delete();
        
        \DB::table('ref_productos')->insert(array (
            0 => 
            array (
                'id' => 5,
                'nombre' => 'SOAT',
                'estado' => 'En proceso',
                'fecha_exp' => '2020-03-10',
                'precredito_id' => 15836,
                'costo' => 100000.0,
                'iva' => 12000.0,
                'num_fact' => '456894',
                'proveedor_id' => 15,
                'producto_id' => 1,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2020-03-20 00:11:20',
                'updated_at' => '2020-03-11 14:32:25',
            ),
            1 => 
            array (
                'id' => 6,
                'nombre' => 'RTM',
                'estado' => 'En proceso',
                'fecha_exp' => '2019-10-10',
                'precredito_id' => 15836,
                'costo' => 140000.0,
                'iva' => 7800.0,
                'num_fact' => '340324',
                'proveedor_id' => 15,
                'producto_id' => 0,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2020-03-13 01:45:20',
                'updated_at' => '2020-03-11 14:32:25',
            ),
            2 => 
            array (
                'id' => 7,
                'nombre' => 'SOAT',
                'estado' => 'Pagado',
                'fecha_exp' => '0000-00-00',
                'precredito_id' => 15835,
                'costo' => 400000.0,
                'iva' => 0.0,
                'num_fact' => NULL,
                'proveedor_id' => 16,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2020-03-13 04:24:02',
                'updated_at' => '2020-03-11 14:42:11',
            ),
            3 => 
            array (
                'id' => 8,
                'nombre' => 'RTM',
                'estado' => 'Pagado',
                'fecha_exp' => '0000-00-00',
                'precredito_id' => 15835,
                'costo' => 150000.0,
                'iva' => 0.0,
                'num_fact' => '53634536',
                'proveedor_id' => 16,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2020-03-13 04:23:49',
                'updated_at' => '2020-03-13 04:00:14',
            ),
            4 => 
            array (
                'id' => 9,
                'nombre' => 'SOAT',
                'estado' => 'Pagado',
                'fecha_exp' => '2020-03-13',
                'precredito_id' => 15835,
                'costo' => 546540.0,
                'iva' => 6546.0,
                'num_fact' => 'FR87878',
                'proveedor_id' => 15,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2020-03-13 04:32:13',
                'updated_at' => '2020-03-13 03:59:34',
            ),
            5 => 
            array (
                'id' => 10,
                'nombre' => 'RTM',
                'estado' => 'Pagado',
                'fecha_exp' => '2020-03-11',
                'precredito_id' => 15835,
                'costo' => 160000.0,
                'iva' => 16000.0,
                'num_fact' => 'DD654544',
                'proveedor_id' => 16,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2020-03-13 04:24:02',
                'updated_at' => '2020-03-11 14:48:17',
            ),
            6 => 
            array (
                'id' => 11,
                'nombre' => 'SOAT',
                'estado' => 'En proceso',
                'fecha_exp' => '2020-03-13',
                'precredito_id' => 15836,
                'costo' => 200000.0,
                'iva' => 232323.0,
                'num_fact' => '',
                'proveedor_id' => 17,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2020-03-13 04:47:44',
                'updated_at' => '2020-03-13 04:47:44',
            ),
            7 => 
            array (
                'id' => 12,
                'nombre' => 'RTM',
                'estado' => 'Pagado',
                'fecha_exp' => '2020-03-18',
                'precredito_id' => 15836,
                'costo' => 222222.0,
                'iva' => 22222.0,
                'num_fact' => '222222',
                'proveedor_id' => 17,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2020-03-20 01:19:37',
                'updated_at' => '2020-03-13 04:47:20',
            ),
            8 => 
            array (
                'id' => 13,
                'nombre' => 'SOAT',
                'estado' => 'Pagado',
                'fecha_exp' => '0000-00-00',
                'precredito_id' => 15837,
                'costo' => 400000.0,
                'iva' => 10000.0,
                'num_fact' => '321321',
                'proveedor_id' => 15,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2020-03-13 04:33:57',
                'updated_at' => '2020-03-13 00:49:46',
            ),
            9 => 
            array (
                'id' => 14,
                'nombre' => 'RTM',
                'estado' => 'Pagado',
                'fecha_exp' => '0000-00-00',
                'precredito_id' => 15837,
                'costo' => 150000.0,
                'iva' => 0.0,
                'num_fact' => '',
                'proveedor_id' => 16,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2020-03-13 04:44:31',
                'updated_at' => '2020-03-13 04:43:41',
            ),
            10 => 
            array (
                'id' => 16,
                'nombre' => '',
                'estado' => 'Pagado',
                'fecha_exp' => NULL,
                'precredito_id' => 0,
                'costo' => NULL,
                'iva' => NULL,
                'num_fact' => NULL,
                'proveedor_id' => NULL,
                'producto_id' => 0,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 0,
                'updated_by' => NULL,
                'created_at' => '2020-03-13 04:22:19',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'nombre' => '',
                'estado' => 'Pagado',
                'fecha_exp' => NULL,
                'precredito_id' => 0,
                'costo' => NULL,
                'iva' => NULL,
                'num_fact' => NULL,
                'proveedor_id' => NULL,
                'producto_id' => 0,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 0,
                'updated_by' => NULL,
                'created_at' => '2020-03-13 04:22:19',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 18,
                'nombre' => '',
                'estado' => 'Pagado',
                'fecha_exp' => NULL,
                'precredito_id' => 0,
                'costo' => NULL,
                'iva' => NULL,
                'num_fact' => NULL,
                'proveedor_id' => NULL,
                'producto_id' => 0,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 0,
                'updated_by' => NULL,
                'created_at' => '2020-03-13 04:22:46',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 19,
                'nombre' => 'SOAT',
                'estado' => 'Pagado',
                'fecha_exp' => '2020-03-13',
                'precredito_id' => 15838,
                'costo' => 400000.0,
                'iva' => 10000.0,
                'num_fact' => '54675745',
                'proveedor_id' => 17,
                'producto_id' => 2,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => '2020-03-20 01:19:37',
                'updated_at' => '2020-03-13 11:06:39',
            ),
            14 => 
            array (
                'id' => 20,
                'nombre' => 'SOAT',
                'estado' => 'En proceso',
                'fecha_exp' => '0000-00-00',
                'precredito_id' => 15839,
                'costo' => 400000.0,
                'iva' => 0.0,
                'num_fact' => NULL,
                'proveedor_id' => 18,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2020-03-20 01:14:26',
                'updated_at' => '2020-03-20 01:14:26',
            ),
            15 => 
            array (
                'id' => 21,
                'nombre' => 'RTM',
                'estado' => 'En proceso',
                'fecha_exp' => '0000-00-00',
                'precredito_id' => 15839,
                'costo' => 200000.0,
                'iva' => 0.0,
                'num_fact' => NULL,
                'proveedor_id' => 18,
                'producto_id' => 3,
                'extra' => NULL,
                'observaciones' => '',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2020-03-20 01:14:26',
                'updated_at' => '2020-03-20 01:14:26',
            ),
        ));
        
        
    }
}
