<?php

use Illuminate\Database\Seeder;

class TercerosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('terceros')->delete();
        
        \DB::table('terceros')->insert(array (
            0 => 
            array (
                'id' => 5,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CDA DEL EJE CAFETERO ',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900352258',
                'digito' => NULL,
                'tel1' => 3172025,
                'tel2' => NULL,
                'dir' => 'AV EL POLLO',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-04 20:00:49',
                'updated_at' => '2019-06-04 20:00:49',
            ),
            1 => 
            array (
                'id' => 6,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CERTIFIMOTOS S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '901171384',
                'digito' => 4,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CALLE 25 # 10-05 LOCOALES 1-2-3 SECTOR LA VIBORA POSTOBON',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 14:38:43',
                'updated_at' => '2019-06-25 14:38:43',
            ),
            2 => 
            array (
                'id' => 7,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'FABIO HUMBERTO PEREZ AVENDANO / FIP SEGUROS',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => '',
                'num_doc' => '93337032',
                'digito' => NULL,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CARRERA 2 # 17-23 LA DORADA',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 14:43:54',
                'updated_at' => '2019-06-25 14:43:54',
            ),
            3 => 
            array (
                'id' => 8,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'DIDIER ALEXANDER ACEVEDO SERNA',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '4514542',
                'digito' => 1,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CARRERA 6 # 17-53 LOCAL 12 CENTRO COMERCIAL LAS FUENTES',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 14:48:11',
                'updated_at' => '2019-06-25 14:48:11',
            ),
            4 => 
            array (
                'id' => 9,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'MAXI-MOTOS S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900985985',
                'digito' => 0,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'BOGOTA',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 14:54:27',
                'updated_at' => '2019-06-25 14:54:27',
            ),
            5 => 
            array (
                'id' => 10,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CONTROL MOTOS IBAGUE S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900465828',
                'digito' => 1,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'IBAGUE',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 14:56:45',
                'updated_at' => '2019-06-25 14:56:45',
            ),
            6 => 
            array (
                'id' => 11,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CENTRO DE DIAGNOSTICO AUTOMOTRIZ TECNI MOTORS QUIMBAYA S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '901026481',
                'digito' => 0,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CALLE 19 CARRERA 7  21 LT - 1',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 15:00:21',
                'updated_at' => '2019-06-25 15:00:21',
            ),
            7 => 
            array (
                'id' => 12,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'MOTOS EL GALLINERAL S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '901111721',
                'digito' => 7,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'SAN GIL',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 15:09:54',
                'updated_at' => '2019-06-25 15:09:54',
            ),
            8 => 
            array (
                'id' => 13,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CAMACHOS ASESORES',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '1075265284',
                'digito' => NULL,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CC LOS COMUNEROS OFICINA  3004',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 15:13:54',
                'updated_at' => '2019-06-25 15:13:54',
            ),
            9 => 
            array (
                'id' => 14,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CENTRO DE DIAGNOSTICO AUTOMOTOR LOS PRIMOS S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900994760',
                'digito' => 9,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CALLE 8 # 28A-04',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 15:18:16',
                'updated_at' => '2019-06-25 15:18:16',
            ),
            10 => 
            array (
                'id' => 15,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CENTRO DE DIAGNOSTICO AUTOMOTRIZ MOTO CLUB AMBALA S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900882724',
                'digito' => 2,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'AV AMBALA # 26-66',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 15:20:22',
                'updated_at' => '2019-06-25 15:20:22',
            ),
            11 => 
            array (
                'id' => 16,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CENTRO DE DIAGNOSTICO AUTOMOTIRZ TECNI MOTORS IBAGUE',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900987009',
                'digito' => 6,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CARRERA 8 # 139-35 BARRIO CEIBA SALADO',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 15:53:03',
                'updated_at' => '2019-06-25 15:53:03',
            ),
            12 => 
            array (
                'id' => 17,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'PAP INVERSIONES LTDA',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900216835',
                'digito' => 6,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CARRERA 6 # 20-19/23',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 15:55:36',
                'updated_at' => '2019-06-25 15:55:36',
            ),
            13 => 
            array (
                'id' => 18,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CENTRO DE DIAGNOSTICO AUTOMOTOR CEDIPLUS SOACHA S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '901114227',
                'digito' => 3,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'CARRERA 4 # 20-84  SOACHA',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:02:34',
                'updated_at' => '2019-06-25 16:02:34',
            ),
            14 => 
            array (
                'id' => 19,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CARSEGUROSPEREIRA LTDA',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900705911',
                'digito' => 6,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CALLE 19  # 6-4B LOCAL 216 ALCIDES AREVALO',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:05:23',
                'updated_at' => '2019-06-25 16:05:23',
            ),
            15 => 
            array (
                'id' => 20,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'MOTO UNION S.A.S ',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900866200',
                'digito' => 8,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CALLE 14  # 10-69  TULUA',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:09:48',
                'updated_at' => '2019-06-25 16:09:48',
            ),
            16 => 
            array (
                'id' => 21,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'LIDERES EN ASISTENCIA PROFESIONAL E INTEGRAL EN SERVICIOS DE TRANSITO Y TRANSPORTE AUTOMOTOR S.A.S  ',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900014037',
                'digito' => 8,
                'tel1' => 2315318,
                'tel2' => NULL,
                'dir' => 'CALLE 39  # 28-09',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:15:38',
                'updated_at' => '2019-06-25 16:15:38',
            ),
            17 => 
            array (
                'id' => 22,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CENTRO DE DIAGNOSTICO AUTOMOTRIZ  UNIMOTOS ',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900750755',
                'digito' => 4,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CARRERA 1 D # 15-58 AVENIDA CIRCUNVALAR',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:20:11',
                'updated_at' => '2019-06-25 16:20:11',
            ),
            18 => 
            array (
                'id' => 23,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'TEAM ADVANCE S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900327922',
                'digito' => 5,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CARRERA 8 # 9-89 ',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:23:23',
                'updated_at' => '2019-06-25 16:23:23',
            ),
            19 => 
            array (
                'id' => 24,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'INSPECCION TECNICA AUTOMOTRIZ INTECO S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900117522',
                'digito' => 1,
                'tel1' => 5440795,
                'tel2' => NULL,
                'dir' => 'CALLE 17  # 115-55',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:26:49',
                'updated_at' => '2019-06-25 16:26:49',
            ),
            20 => 
            array (
                'id' => 25,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CENTRO DE ENSE;ANZA AUTOMOVILISTICA CACIQUE TONE S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900750383',
                'digito' => 8,
                'tel1' => 8502889,
                'tel2' => NULL,
                'dir' => 'CARRERA 31 # 24-05  URRAO',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:34:00',
                'updated_at' => '2019-06-25 16:34:00',
            ),
            21 => 
            array (
                'id' => 26,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CENTRO DE ENSENANZA AUTOMOVILISTICA CONDUCALDAS T.P S,A,S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900655924',
                'digito' => 6,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CALLE 28 # 10-12',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:36:05',
                'updated_at' => '2019-06-25 16:36:05',
            ),
            22 => 
            array (
                'id' => 27,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'JOSE NORBERTO SANCHEZ MARTINEZ S.A.S  CDA CARTAGO',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900339941',
                'digito' => 7,
                'tel1' => 2126947,
                'tel2' => NULL,
                'dir' => 'CALLE 4 # 6-32',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:38:59',
                'updated_at' => '2019-06-25 16:38:59',
            ),
            23 => 
            array (
                'id' => 28,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'MOTO CASCOS MANIZALEZ',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '8978975',
                'digito' => NULL,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CALLE 15 # 22-51',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2019-06-25 16:43:19',
                'updated_at' => '2019-06-25 16:43:19',
            ),
            24 => 
            array (
                'id' => 29,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'CDA MOTOMAS LTDA',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900135344',
                'digito' => NULL,
                'tel1' => 6263583,
                'tel2' => NULL,
                'dir' => 'AV 1 DE MAYO # 29-33',
                'mun_id' => 209,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 30,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'J&M SEGUROS',
                'pnombre' => 'Monica',
                'snombre' => 'Vanessa',
                'papellido' => 'Ospina',
                'sapellido' => 'Ramirez',
                'tipo_doc' => '',
                'num_doc' => '1054564555',
                'digito' => NULL,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'CALLE 11 #3- 21 CENTRO, LA DORADA, CALDAS 
',
                'mun_id' => 568,
                'email' => 'ospinamonica15@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 31,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'CDA CARLLANOS SAS',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900633942',
                'digito' => 4,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'CLL 31 N 24-93',
                'mun_id' => 1190,
                'email' => 'carteracarllanos@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 32,
                'tipo' => 'Proveedor',
                'regimen' => '',
                'razon_social' => 'José Danilo Lopez Ramirez',
                'pnombre' => 'Jose',
                'snombre' => 'Danilo',
                'papellido' => 'López',
                'sapellido' => 'Ramírez',
                'tipo_doc' => '',
                'num_doc' => '10114626',
                'digito' => NULL,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'Cra 6 #17-62 Edif Fegove ofc 203',
                'mun_id' => 1,
                'email' => 'jlopezra64@hotmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 33,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'Grupo CARDISEL SAS',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900152032',
                'digito' => 2,
                'tel1' => 36,
                'tel2' => NULL,
                'dir' => 'Cra 7 # 43-96 ',
                'mun_id' => 1,
                'email' => 'contabilidad@cardisel.com.co',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 34,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'CONTROL AUTOS DE GIRARDOT SAS',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900554151',
                'digito' => 6,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'CR 10#38-05 FRENTE AL COLEGIO DEPARTAMENTAL',
                'mun_id' => 480,
                'email' => 'monicaprada@cdagirardot.com.co',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 35,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'Rapitienda parque Olaya',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '1088247727',
                'digito' => NULL,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'AV 30 DE AGOSTO CON CALLE 21 ESQUINA,ESTACION TERPEL PARQUE OLAYA',
                'mun_id' => 1,
                'email' => 'RAPIOLAYA@GMAIL.COM',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 36,
                'tipo' => 'Proveedor',
                'regimen' => 'No responsable de IVA',
                'razon_social' => 'Sociedad Familiar SAS',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900391327',
                'digito' => 4,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'carrera 7 numero 22-46',
                'mun_id' => 1069,
                'email' => 'cdasanmiguel@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 37,
                'tipo' => 'Proveedor',
                'regimen' => '',
                'razon_social' => 'PUNTO SOAT BUGA',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '111615904',
                'digito' => 8,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'Carrera 8 # 6-01',
                'mun_id' => 497,
                'email' => 'lf.seguros@outlook.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 38,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => NULL,
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900200811',
                'digito' => 1,
                'tel1' => 36,
                'tel2' => NULL,
                'dir' => 'CRA 2 CON CALLE 20 ESQUINA LA DORADA, CALDAS',
                'mun_id' => 568,
                'email' => 'diagnosticentro.ladorada@hotmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 39,
                'tipo' => 'Proveedor',
                'regimen' => '',
                'razon_social' => 'CERTIMOTOSGIR S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900814092',
                'digito' => NULL,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'CRA 7A NO. 29-10',
                'mun_id' => 480,
                'email' => 'CERTIMOTOSGIR@HOTMAIL.COM',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 40,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'CDA del Tolima',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900149510',
                'digito' => 0,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'calle 20 1-20 Sur Arado',
                'mun_id' => 533,
                'email' => 'cdadeltolima@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 41,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'DIADNOSTICENTRO LA DORADA LTDA',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900200811',
                'digito' => 1,
                'tel1' => 368571582,
                'tel2' => NULL,
                'dir' => 'CRA 2 CON CALLE 20 ESQUINA',
                'mun_id' => 568,
                'email' => 'diagnosticentro.ladorada@hotmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 42,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'CDA CHECK AND GO SAS',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '901186562',
                'digito' => 4,
                'tel1' => 2147483647,
                'tel2' => 2147483647,
                'dir' => 'CRA 6 # 23-30',
                'mun_id' => 533,
                'email' => 'info@chechanddgomotos.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 43,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'CENTRO DE DIAGNOSTICO AUTOMOTRIZ DEL HUILA S.A.S.',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900113252',
                'digito' => 1,
                'tel1' => 338761336,
                'tel2' => NULL,
                'dir' => 'CARRERA 7A  55-44',
                'mun_id' => 710,
                'email' => 'cdahuila@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 44,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'CENTRO DE DIAGNOSTICO AUTOMOTRIZ CDA SAN PEDRO NEIVA S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '901159620',
                'digito' => 9,
                'tel1' => 388667097,
                'tel2' => NULL,
                'dir' => 'CALLE 6 # 2-40',
                'mun_id' => 710,
                'email' => 'CDASANPEDRONEIVA@GMAIL.COM',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 45,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'CDA DEL SUR DEL TOLIMA',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900877585',
                'digito' => 5,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'Calle 10 N 14E 1 41',
                'mun_id' => 293,
                'email' => 'cdadelsurdeltolima@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 46,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'Control Autos de Fusagasugá S.A.S.',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900336502',
                'digito' => 3,
                'tel1' => 318676504,
                'tel2' => NULL,
                'dir' => 'Trasversal 28 # 5 - 88 Vía Novilleros',
                'mun_id' => 462,
                'email' => 'controlautos@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 47,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'Centro de Diagnóstico Automotor cda Ángeles del Río sas',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900761883',
                'digito' => 6,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'Calle 24 # 12-22 Centro',
                'mun_id' => 1,
                'email' => 'cdaangelesdelrio@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 48,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'ASISTIMOTOS SEGUROS S.A.S',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '901169429',
                'digito' => 0,
                'tel1' => 363172520,
                'tel2' => NULL,
                'dir' => 'CALLE 18 #11-56',
                'mun_id' => 1,
                'email' => 'cartera@asistimotos.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 49,
                'tipo' => 'Proveedor',
                'regimen' => NULL,
                'razon_social' => 'ANONIMO',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '000000000',
                'digito' => NULL,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'NA',
                'mun_id' => NULL,
                'email' => NULL,
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 50,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'CDA LA REVISIÓN SAS',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '901012825',
                'digito' => NULL,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'Cra 5 N 91 - 61',
                'mun_id' => 533,
                'email' => 'cdalarevisionsas@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 51,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'Automás Peritar SAS',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900871356',
                'digito' => 8,
                'tel1' => 0,
                'tel2' => NULL,
                'dir' => 'Carrera 10 # 38-06',
                'mun_id' => 1,
                'email' => 'director.peritar@cdaautomas.com.co',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 52,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'Ambientalcenter SAS',
                'pnombre' => 'Santiago',
                'snombre' => NULL,
                'papellido' => 'Lesmes',
                'sapellido' => 'Losada',
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900499706',
                'digito' => 8,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'Calle 26 34 77-79 B. San Benito',
                'mun_id' => 1190,
                'email' => 'cdambientalcenter@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => '2020-10-27 00:00:00',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 53,
                'tipo' => 'Proveedor',
                'regimen' => 'Regimen comun',
                'razon_social' => 'Cda diagnósticar Ibagué',
                'pnombre' => NULL,
                'snombre' => NULL,
                'papellido' => NULL,
                'sapellido' => NULL,
                'tipo_doc' => 'Nit empresarial',
                'num_doc' => '900149510',
                'digito' => NULL,
                'tel1' => 2147483647,
                'tel2' => NULL,
                'dir' => 'Cr 20 sur N. 107/102 km 3 vía picaleña',
                'mun_id' => 533,
                'email' => 'contabilidadinverfuturo@gmail.com',
                'created_by' => 2,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}
